<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
                    <?
                        if ($this->node) {
                                echo $this->action('view-folder-navigation', 'widgets_folder', 'hold', array('node' => $this->node));
                        }
                        elseif ($this->nprt) {
                                echo $this->action('view-folder-navigation-peraturan', 'widgets_folder', 'hold', array('nprt' => $this->nprt));
                        }
                        elseif ($this->npts) {
                                echo $this->action('view-folder-navigation-putusan', 'widgets_folder', 'hold', array('npts' => $this->npts));
                        }
                
                
                        if ($this->nprt) {
                                echo $this->action('viewer', 'widgets_catalog', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt));
                        }
                        elseif ($this->npts) {
                                echo $this->action('viewer', 'widgets_catalog', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts));
                        }
                        else {
                                echo $this->action('viewer', 'widgets_catalog', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node));
                        }
                    ?>
                    <div class="clean"></div>
                    <div class="padding_top_5"></div>
                    <?=$this->action('document', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid)); ?>
                    <div class="clean"></div>
                    <div class="padding_top_5"></div>
                    <?=$this->action('view-folder', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid)); ?>
                    <div class="padding_top_5"></div>
                    <?
                            if ($this->nprt) {
                                    echo $this->action('view-dasar-hukum', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt));
                            }
                            elseif ($this->npts) {
                                    echo $this->action('view-dasar-hukum', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts));
                            }
                            else {
                                    echo $this->action('view-dasar-hukum', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node));
                            }
                    ?>
                    <div class="padding_top_5"></div>
                    <?
                            if ($this->nprt) {
                                    echo $this->action('peraturan-pelaksana', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt));
                            }
                            elseif ($this->npts) {
                                    echo $this->action('peraturan-pelaksana', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts));
                            }
                            else {
                                    echo $this->action('peraturan-pelaksana', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node));
                            }
                    ?>
                    <div class="padding_top_5"></div>
                    <?
                            if ($this->nprt) {
                                    echo $this->action('view-history', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt));
                            }
                            elseif ($this->npts) {
                                    echo $this->action('view-history', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts));
                            }
                            else {
                                    echo $this->action('view-history', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node));
                            }
                    ?>

                    <?=$this->action('other', 'widgets_relation', 'hold', array('parent' => $this->catalogGuid)); ?>

                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->