<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first" style="border-right: 1px solid #cecece; ">
                    <?=$this->action('miniprofile','index','hol-site');?>
                    <form id="searchForm" method="post" action="<?=$this->baseUrl();?>/cari">
                        <input size="20" name="keyword" id="keyword" type="text">
                        <input name="submit" value="Cari" class="btn-blue" type="submit">
                    </form>
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>

                </div>
                <div class="kolom widthcontent5" style="padding-left: 5px;">
                    <br/><div class="box box-info">
                        File kosong, silahkan hubungi kami di <a href="mailto:layanan@hukumonline.com">layanan@hukumonline.com</a>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->