<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">

                    <br/>
                    <?
                        if ($this->node) {
                            echo $this->action('view-folder-navigation', 'widgets_folder', 'hold', array('node' => $this->node));
                        }
                        elseif ($this->nprt) {
                            echo $this->action('view-folder-navigation-peraturan', 'widgets_folder', 'hold', array('nprt' => $this->nprt));
                        }
                        elseif ($this->npts) {
                            echo $this->action('view-folder-navigation-putusan', 'widgets_folder', 'hold', array('npts' => $this->npts));
                        }
                    ?>

                    <?=$this->action('browse','browser','hold'); ?>

                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->