<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('miniprofile','index','hol-site');?>
                    <? if ($this->aData['totalCount'] > 0) { ?>
                    <?=$this->action('fprofile','widgets_search','search',array('query'=>$this->query,'ct'=>$this->ct));?>
                    <?=$this->action('fclinic','widgets_search','search',array('query'=>$this->query,'ct'=>$this->ct));?>
                    <?=$this->action('fhold','widgets_search','search',array('query'=>$this->query,'ct'=>$this->ct));?>
                    <? } else { ?>
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                    <? } ?>
                </div>
                <div class="kolom" style="width: 723px;border-left: 1px solid #cecece; padding-left:10px;">
                	<div style="padding-top:20px;"></div>
                    <div class="align-right">
                        <form id="searchForm" method="post" action="<?=$this->baseUrl();?>/cari">
                            <input name="submit" value="Cari" class="btn-blue" type="submit">
                            <input size="40" name="keyword" id="keyword" type="text" value="<?=$this->layout()->searchQuery;?>">
                            <select name="category" id="category">
                                <option value="">Pilih:</option>
                                <option value="article">Artikel</option>
                                <option value="klinik">Klinik</option>
                                <option value="(kutu_peraturan OR kutu_peraturan_kolonial OR kutu_rancangan_peraturan OR kutu_putusan)">Peraturan</option>
                            </select>
                        </form>
                        &raquo;&nbsp;<a href="<?=ROOT_URL;?>/cari/lanjutan" class="bb">Pencarian lanjutan</a>
                    </div>
                    <div style="clear:both"></div>
                    <fieldset>
                            <legend>Sekitar&nbsp;<b><?=$this->aData['totalCount'];?></b> hasil (<b><?=$this->time;?></b> detik)</legend>
                            <? if(isset($this->hits->spellcheck->suggestions->collation)) { ?>
                            <table>
                            <tr>
                                <td style="color: #003366;font-size: 12px;">
                                <form id="searchForm" method="POST" action="<?=$this->baseUrl();?>/cari">
                                Apa maksudnya : <?=$this->hits->spellcheck->suggestions->collation ?>
                                <input name="cari" type="hidden" value="<?=$this->hits->spellcheck->suggestions->collation ?>" />
                                <input value="Ya" class="btn-blue" type="submit" />
                                </form>
                                </td>
                            </tr>
                            </table>
                            <? } ?><br>
                            <? if ($this->aData['totalCount'] > 0) { ?>
                            <div id='catalogContent'></div><br>
                            <table>
                            <tr>
                                <td width=25%>&nbsp;</td>
                                <td align="center"><div id='catalogSearchPagination' class="pagination"></div></td>
                            </tr>
                            </table>
                            <? } else { ?>
                            <div class="ta-center"><h1>.:Data Tidak Ditemukan:.</h1></div>
                            <? } ?>
                    </fieldset>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->
<script>

$(document).ready(function(){

    var isFirstTime = 1;

    var myPageIndex = 0;

    $("#category").val('<?=$this->layout()->categorySearchQuery; ?>');

    $("#catalogSearchPagination").pagination(<?=$this->aData['totalCount'];?>,
    {items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
    );

    function handlePaginationClick(new_page_index, pagination_container)
    {
        myPageIndex = new_page_index;
        myStart = (<?=$this->aData['limit'];?> * myPageIndex);

        if(true)
        {
            if($('#tblCatalogPager-'+myPageIndex).length==0)
            {
                $.getJSON('<?=$this->baseUrl();?>/api/catalog/getcatalogsearch/query/<?=$this->query;?>/ct/<?=$this->ct?>/start/'+myStart+'/limit/<?=$this->aData['limit'];?>', '', searchResult);
            }
            else
                showCatalogContent();
        }
        return false;
    }

    function searchResult(res)
    {
        size = res.catalogs.length;
        var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table width="100%" class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
        tblRow +=

                "<tr valign=top>"
                +"<td>"
                +"<div class='td_peraturan5'>"
                +"<div style='height:auto;'>"
                +"<div class='searchcontent'>";

        for(i=0;i<size;i++)
        {
            tblRow +=

                    res.catalogs[i].subTitle
                    +res.catalogs[i].title+"&nbsp;&ndash;&nbsp;<abbr>"+res.catalogs[i].profile+"</abbr>"
                    +"<small>"+res.catalogs[i].description+"</small>"
                    +"<span class='subtitle'>"+res.catalogs[i].publishedDate+"</span>&nbsp;&ndash;&nbsp;<cite>"+res.catalogs[i].score+"</cite><br><br>";
        }

        tblRow +=

                "</div>"
                +"</div>"
                +"</div>"
                +"</td>"
                +"</tr>";

        tblRow += "</table>";
        $(tblRow).appendTo("#catalogContent");
        showCatalogContent();

    }
    function showCatalogContent()
    {
        $('.tblCatalogPager').hide();
        $('#tblCatalogPager-'+myPageIndex).show();
        if(!isFirstTime)
                Scroller.scroll();
        isFirstTime = 0;
    }

});

</script>