<? for($i=0;$i<$this->numberOfRows;$i++) {

    $registry = Zend_Registry::getInstance();
    $config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
    $cdn = $config->getOption('cdn');
    $sDir = $cdn['static']['url']['images'];
    $thumb = "";

    $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($this->data[$i][1],'RELATED_IMAGE');
    $itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';

    if (Pandamp_Lib_Formater::thumb_exists($sDir ."/". $itemGuid . ".jpg")) 	{ $thumb = $sDir ."/". $itemGuid . ".jpg"; 	}
    if (Pandamp_Lib_Formater::thumb_exists($sDir ."/". $itemGuid . ".gif")) 	{ $thumb = $sDir ."/". $itemGuid . ".gif"; 	}
    if (Pandamp_Lib_Formater::thumb_exists($sDir ."/". $itemGuid . ".png")) 	{ $thumb = $sDir ."/". $itemGuid . ".png"; 	}

    if ($thumb == "") { $thumb = $this->cdn('images')."/slider/image1.jpg"; }

    $screenshot = "<img src=\"".$thumb."\"  vspace=\"0\" width=\"104\" border=\"0\" hspace=\"0\" align=\"left\" />";

?>
<h5><?=$this->data[$i][4];?></h5>
<div class="colgroup leading">
    <? if ($thumb=="") { $screenshot=""; } else { ?>
    <div class="width1 column first ta-center">
        <?=$screenshot;?>
    </div>
    <? } ?>
    <div class="column" style="width:570px;">
        <a href="<?=ROOT_URL;?>/berita/baca/<?=$this->data[$i][1];?>/<?=$this->data[$i][2];?>"><b class="big"><?=$this->data[$i][0];?></b></a><br/>
        <p><?=$this->data[$i][3];?></p>
    </div>
</div>
<div class="clearfix"></div>
<? } ?>