<?
$sDir = $this->getRemoteImageUrl();
$thumb = "";

$rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($this->catalogGuid,'RELATED_IMAGE');
$itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';
if (!empty($itemGuid))
{
    if (Pandamp_Lib_Formater::thumb_exists($sDir."/".$itemGuid.".jpg")) 	{ $thumb = $sDir."/".$itemGuid.".jpg"; 	}
    if (Pandamp_Lib_Formater::thumb_exists($sDir."/".$itemGuid.".gif")) 	{ $thumb = $sDir."/".$itemGuid.".gif"; 	}
    if (Pandamp_Lib_Formater::thumb_exists($sDir."/".$itemGuid.".png")) 	{ $thumb = $sDir."/".$itemGuid.".png"; 	}
}

$screenshot = "<img src=\"".$thumb."\" width=\"90\" />";

?>

<div class="mitraisi">
    <div class="align-left" style="width:550px;">
	<? if (!empty($thumb)) : ?>
    <div class="image"><?=$screenshot; ?></div>
    <? endif; ?>
    <a href="<?=$this->baseUrl(); ?>/klinik/mitra/<?=$this->catalogGuid; ?>" class="klinikbrowse"><b><?=$this->title; ?></b></a>
    <?=$this->content; ?>
    
    </div>
    <div class="align-right"><a href="<?=$this->baseUrl(); ?>/klinik/kontributor/<?=$this->catalogGuid;?>" class="klinikbrowse">Kontribusi:<?=$this->ct;?> jawaban</a></div>
    <div style="clear:both"></div>
</div>
