<div class="align-left">
    <div id="judul2">Aktual</div>
</div>
<div class="align-right">&raquo;&nbsp;<a href="" class="bb">index</a></div>
<div class="clean bt_blue"></div>
<div class="margin_mintop_8"></div>
<ul id="news">
<?
foreach($this->rowset as $row)
{
?>
    <li><a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$row['guid']; ?>/<?=$row['shortTitle']; ?>" class="aktual"><?=$this->getCatalogAttribute($row['guid'],'fixedTitle') . ' ['.date("d/m",strtotime($row['createdDate'])) . ']';  ?></a></li>
<?
}
?>
</ul>
