<div class="align-left">
    <div id="judul2"><?=$this->title;?></div>
</div>
<div class="align-right">&raquo;&nbsp;<a href="" class="bb">index</a></div>
<div class="clear">&nbsp;</div>
<div class="bt_blue"></div>
<ul class="hol_berita_1">
    <? for($i=0; $i<$this->numberOfRows;$i++) { ?>
    <li>
        <h5 class="l_blue_hol">
            <a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>"><?=$this->data[$i][0]; ?></a>
        </h5>
        <span class="author">[<?=$this->data[$i][1]; ?>]</span>
        <?=Pandamp_Lib_Formater::string_limit_words($this->data[$i][2],10);?>
        <div class="clean"></div>
        <nav>
            <img src="<?=$this->cdn('images'); ?>/comment.jpg" width="13" height="9" /><a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>#comments" class="bb"> <?=$this->data[$i][3]; ?> tanggapan </a> |<a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5];?>" class="bb"> Selengkapnya </a>
        </nav>
	</li>         
    <? } ?>
</ul>    
<div class="clean"></div>