<div class="align-left">
    <div id="judul2">
        Isu Hangat
    </div>
</div>
<div class="align-right">
    &raquo;&nbsp;<a href="" class="bb">index</a>
</div>
<div class="clear">&nbsp;</div>
<div style="border-top:1px solid #87CEFA"></div>
<table class="no-style full">
    <tbody>
        <? for($i=0; $i<$this->numberOfRows;$i++) { ?>
        <tr>
            <td class="ta-left">&raquo;
                <a href="<?=$this->baseUrl(); ?>/berita/isuhangat/<?=$this->data[$i][3]; ?>/<?=$this->data[$i][1]; ?>" class="aktual">
                    <b><?=$this->data[$i][0]; ?></b>
                </a>
            </td>
        </tr>
        <? } ?>
    </tbody>
</table>
