<div class="align-left">
    <div id="judul2"><a href="<?=ROOT_URL;?>/klinik" class="akt">Klinik Hukum</a></div>
</div>
<div class="align-right">
    <a href="http://www.facebook.com/profile.php?id=100000049397040&ref=mf" target="_blank"><img src="<?=$this->cdn('images');?>/facebook.png" alt="Facebook" name="Facebook" width="15" height="15" border="0" id="Facebook" /></a>
    <a href="http://www.twitter.com/klinikhukum" target="_blank"><img src="<?=$this->cdn('images');?>/twitterhol.png" alt="Twitter" name="Twitter" width="15" height="15" border="0" id="Twitter" /></a>
</div>
<div class="clear">&nbsp;</div>
<div class="bt_blue"></div>
<ul class="hol_berita_1">
<? for($i=0; $i<$this->numberOfRows;$i++) { ?>
	<li>
        <h5 class="l_blue_hol"><a href="<?=$this->baseUrl(); ?>/klinik/detail/<?=$this->data[$i][3];?>"><?=$this->data[$i][0];?></a></h5>
        <span class="date">[<?=$this->data[$i][4]; ?>]</span>
        <?=Pandamp_Lib_Formater::string_limit_words($this->data[$i][1],20);?>
	</li>      
<? } ?>
</ul>
&ndash;&nbsp;<a href="<?=$this->baseUrl(); ?>/klinik/terbaru" class="bb">index</a>&nbsp;&ndash;
<div class="clean"></div>

