<div class="align-left">
    <div id="judul2">Kolom</div>
</div>
<div class="align-right">&raquo;&nbsp;<a href="" class="bb">index</a></div>
<div class="clear">&nbsp;</div>
<div class="bt_blue"></div>
<ul class="hol_berita_1">
    <?
    $registry = Zend_Registry::getInstance();
    $config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
    $cdn = $config->getOption('cdn');
    $sDir = $cdn['static']['url']['images'];
    for($i=0; $i<$this->numberOfRows;$i++) {

        $thumb = "";
        $guid = $this->data[$i][4];

        $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($guid,'RELATED_IMAGE');
        $itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';
		$chkDir = $sDir."/".$guid."/".$itemGuid;
		if (@getimagesize($chkDir))
		{
			$pict = $sDir ."/". $guid ."/". $itemGuid;
		}
		else 
		{
			$pict = $sDir ."/". $itemGuid;
		}
		
	
		if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) 	{ $thumb = $pict . ".jpg"; 	}
		if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) 	{ $thumb = $pict . ".gif"; 	}
		if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) 	{ $thumb = $pict . ".png"; 	}
        
        $screenshot = "<img src=\"".$thumb."\" width=\"40\" height=\"40\" />";

    ?>
    	<li>
            <h5 class="l_blue_hol">
                <a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>"><?=$this->data[$i][0]; ?></a>
            </h5>
        	<? if (!empty($thumb)) : ?>
            <?=$screenshot; ?>
            <? endif; ?>
            <!--<dt class="author">[<?//=$this->data[$i][1]; ?>]</dt>-->
            <?=Pandamp_Lib_Formater::string_limit_words($this->data[$i][2],10);?>
            <div class="clean"></div>
            <nav class="padding_top_5">
                <img src="<?=$this->cdn('images'); ?>/comment.jpg" width="13" height="9" /><a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>#comments" class="bb"> <?=$this->data[$i][3]; ?> tanggapan </a> |<a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5];?>" class="bb"> Selengkapnya </a>
            </nav>
   		</li>
        <div class="clean"></div>
    <? } ?>
</ul>    
<div class="clean"></div>