<div class="align-left">
    <div id="judul2">Komunitas</div>
</div>
<div class="align-right">&raquo;&nbsp;<a href="" class="bb">index</a></div>
<div class="clean"></div>
<ul class="hol_berita_1">
<?
$registry = Zend_Registry::getInstance();
$config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
$cdn = $config->getOption('cdn');
$sDir = $cdn['static']['url']['images'];
for($i=0; $i<$this->numberOfRows;$i++) {

    $thumb = "";
    $guid = $this->data[$i][2];

    $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($guid,'RELATED_IMAGE');
    $itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';

	$chkDir = $sDir."/".$guid."/".$itemGuid;
	if (@getimagesize($chkDir))
	{
		$pict = $sDir ."/". $guid ."/". $itemGuid;
	}
	else 
	{
		$pict = $sDir ."/". $itemGuid;
	}
	

	if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) 	{ $thumb = $pict . ".jpg"; 	}
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) 	{ $thumb = $pict . ".gif"; 	}
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) 	{ $thumb = $pict . ".png"; 	}
    
    //if ($thumb == "") { $thumb = $this->cdn('images')."/nothumb.jpg"; }
    $screenshot = "<img src=\"".$thumb."\" width=\"40\" height=\"40\" />";

?>
    <li>
    	<? if (!empty($thumb)) : ?>
        <?=$screenshot; ?>
        <? endif; ?>
        <h5 class="l_blue_hol">
            <a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][2]; ?>/<?=$this->data[$i][3]; ?>" title="<?=$this->data[$i][1]; ?>"><?=$this->data[$i][0]; ?></a>
        </h5>
        <div class="clean"></div>
    </li>
<? } ?>
</ul>
<div class="clean"></div>
