<div class="align-left">
    <div id="judul2">
        <a href="<?=ROOT_URL;?>/pusatdata" class="akt">Pusat Data</a>
    </div>
</div>
<div class="clear">&nbsp;</div>
<div style="border-top:1px solid #87CEFA;width:95%;"></div>
<div id="tabs" style="width: 235px;">
    <ul>
        <li><a href="#tabs-1">Baru</a></li>
        <li><a href="#tabs-2">Peraturan</a></li>
        <li><a href="#tabs-3">Pilihan</a></li>
    </ul>
    <div id="tabs-1">
    	<div class="box box-error closeable" id="msg" style="display:none;"></div>
        <?=$this->ajaxActionRenderer(ROOT_URL.'/peraturan');?>
    </div>
    <div id="tabs-2">
        <?=$this->action('peraturanpilihan','widgets_content','hol-site'); ?>
    </div>
    <div id="tabs-3">Nam dui erat, auctor a, dignissim quis, sollicitudin eu, felis. Pellentesque nisi urna, interdum eget, sagittis et, consequat vestibulum, lacus. Mauris porttitor ullamcorper augue.</div>
</div>
