<div class="padding_top_10"></div>
<div class="align-left">
    <div id="judul2">
        Resensi
    </div>
</div>
<div class="align-right">
    &raquo;&nbsp;<a href="" class="bb">index</a>
</div>
<div class="clean"></div>
<div class="bt_blue"></div>
<table class="style_1 full">
    <tbody>
	<? if ($this->numberOfRows == 0) { ?>
	<tr>
            <td colspan="2">Resensi kosong</td>
	</tr>
	<? } for ($i = 0; $i < $this->rows; $i++) { ?>
	<tr>
	<? for ($j = 0; $j < $this->columns; $j++) { ?>
	   	<td class="hb_1">
            <h5 class="l_blue_hol">
                <a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i + ($j * $this->rows)][4]; ?>/<?=$this->data[$i + ($j * $this->rows)][5]; ?>"><?=$this->data[$i + ($j * $this->rows)][0]; ?></a>
            </h5>
		<?
    $registry = Zend_Registry::getInstance();
    $config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
    $cdn = $config->getOption('cdn');
    $sDir = $cdn['static']['url']['images'];
//		$sDir = 'uploads/images';
		$thumb = "";

                $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($this->data[$i + ($j * $this->rows)][4],'RELATED_IMAGE');
		$itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';

		if ($itemGuid) {
		if (Pandamp_Lib_Formater::thumb_exists($sDir ."/tn_". $itemGuid . ".jpg")) 	{ $thumb = $sDir ."/tn_". $itemGuid . ".jpg"; 	}
		if (Pandamp_Lib_Formater::thumb_exists($sDir ."/tn_". $itemGuid . ".gif")) 	{ $thumb = $sDir ."/tn_". $itemGuid . ".gif"; 	}
		if (Pandamp_Lib_Formater::thumb_exists($sDir ."/tn_". $itemGuid . ".png")) 	{ $thumb = $sDir ."/tn_". $itemGuid . ".png"; 	}
		}

		//if ($thumb == "") { $thumb = $this->cdn('images')."/nothumb.jpg"; }
			$screenshot = "<img src=\"".$thumb."\" width=\"60\" height=\"60\" class=\"img1\" />";

		?>
		
		<? if (!empty($thumb)) : ?>
	    <?=$screenshot; ?>
	    <? endif; ?>
		<span class="author">[<?=$this->data[$i + ($j * $this->rows)][1]; ?>]</span>
	   	<?=Pandamp_Lib_Formater::string_limit_words($this->data[$i + ($j * $this->rows)][2],10); ?>
	   	<div class="clean"></div>
	   	<nav>
        	<img src="<?=$this->cdn('images');?>/comment.jpg" width="13" height="9" /><a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i + ($j * $this->rows)][4]; ?>/<?=$this->data[$i + ($j * $this->rows)][5]; ?>#comments" class="bb"> <?=$this->data[$i + ($j * $this->rows)][3]; ?> tanggapan </a> |<a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i + ($j * $this->rows)][4]; ?>/<?=$this->data[$i + ($j * $this->rows)][5]; ?>" class="bb"> Selengkapnya </a>
       	</nav>
	   	</td>
	<? } ?>
	</tr>
	<? } ?>
    </tbody>
</table>
<div class="clean"></div>