<div style="padding-top:15px;"></div>
<div class="align-left">
    <div id="judul2">
        Resensi
    </div>
</div>
<div class="align-right">
    &raquo;&nbsp;<a href="" class="bb">index</a>
</div>
<div class="clear">&nbsp;</div>
<div style="border-top:1px solid #87CEFA;"></div>
<table class="no-style full">
    <tbody>
	<? if ($this->numberOfRows == 0) { ?>
	<tr>
            <td colspan="2">Resensi kosong</td>
	</tr>
	<? } for ($i = 0; $i < $this->rows; $i++) { ?>
	<tr>
	<? for ($j = 0; $j < $this->columns; $j++) { ?>
	   	<td>
                    <header>
                        <a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i + ($j * $this->rows)][4]; ?>/<?=$this->data[$i + ($j * $this->rows)][5]; ?>" class="aktual"><b><?=$this->data[$i + ($j * $this->rows)][0]; ?></b></a>
                    </header>
	   	<dl class="first">
		<?
    $registry = Zend_Registry::getInstance();
    $config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
    $cdn = $config->getOption('cdn');
    $sDir = $cdn['static']['url']['images'];
//		$sDir = 'uploads/images';
		$thumb = "";

                $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($this->data[$i + ($j * $this->rows)][4],'RELATED_IMAGE');
		$itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';

		if ($itemGuid) {
		if (Pandamp_Lib_Formater::thumb_exists($sDir ."/tn_". $itemGuid . ".jpg")) 	{ $thumb = $sDir ."/tn_". $itemGuid . ".jpg"; 	}
		if (Pandamp_Lib_Formater::thumb_exists($sDir ."/tn_". $itemGuid . ".gif")) 	{ $thumb = $sDir ."/tn_". $itemGuid . ".gif"; 	}
		if (Pandamp_Lib_Formater::thumb_exists($sDir ."/tn_". $itemGuid . ".png")) 	{ $thumb = $sDir ."/tn_". $itemGuid . ".png"; 	}
		}

		//if ($thumb == "") { $thumb = $this->cdn('images')."/nothumb.jpg"; }
			$screenshot = "<img src=\"".$thumb."\" vspace=\"0\" width=\"40\" border=\"0\" height=\"40\" hspace=\"0\" align=\"left\" />";

		?>
		
		<? if (!empty($thumb)) : ?>
	    <dt style="float:left;padding:2px;margin:2px;"><?=$screenshot; ?></dt>
	    <? endif; ?>
		<dt class="author">[<?=$this->data[$i + ($j * $this->rows)][1]; ?>]</dt>
	   	<dd class="last"><?=Pandamp_Lib_Formater::string_limit_words($this->data[$i + ($j * $this->rows)][2],10); ?></dd>
	   	</dl>
	   	<nav>
                    <img src="<?=$this->cdn('images');?>/comment.jpg" width="13" height="9" /><a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i + ($j * $this->rows)][4]; ?>/<?=$this->data[$i + ($j * $this->rows)][5]; ?>#comments" class="bb"> <?=$this->data[$i + ($j * $this->rows)][3]; ?> tanggapan </a> |<a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i + ($j * $this->rows)][4]; ?>/<?=$this->data[$i + ($j * $this->rows)][5]; ?>" class="bb"> Selengkapnya </a>
                </nav>
	   	</td>
	<? } ?>
	</tr>
	<? } ?>
    </tbody>
</table>
<div class="clean"></div>