<div class="align-left">
    <div id="judul2">Utama</div>
</div>
<div class="align-right">&raquo;&nbsp;<a href="" class="bb">index</a></div>
<div class="clear">&nbsp;</div>
<div class="bt_blue padding_top_5"></div>
<div id="featured">
<ul class="ui-tabs-nav">
<?php
$registry = Zend_Registry::getInstance();
$config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
$cdn = $config->getOption('cdn');
$sDir = $cdn['static']['url']['images'];
for($i=0; $i<$this->numberOfRows;$i++) {

    $thumb = "";
    $guid = $this->data[$i][2];

    $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($guid,'RELATED_IMAGE');
    $itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';
    
	$chkDir = $sDir."/".$guid."/".$itemGuid;
	
	if (@getimagesize($chkDir))
	{
	$pict = $sDir ."/". $guid ."/". $itemGuid;
	}
	else
	{
	$pict = $sDir ."/". $itemGuid;
	}
	
	
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) { $thumb = $pict . ".jpg"; }
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) { $thumb = $pict . ".gif"; }
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) { $thumb = $pict . ".png"; }

    if ($thumb == "") { $thumb = $this->cdn('images')."/nothumb.jpg"; }

    $small_screenshot = "<img src=\"".$thumb."\" alt=\"".$this->data[$i][0]."\" width=\"80\" height=\"50\" />";

	$j = $i+1; 

?>


	<? if ($j==1) { ?>
	<li class="ui-tabs-nav-item ui-tabs-selected" id="nav-fragment-<?=$j;?>"><a href="#fragment-<?=$j;?>"><?=$small_screenshot; ?></a></li>
	<? } else { ?>
	<li class="ui-tabs-nav-item" id="nav-fragment-<?=$j;?>"><a href="#fragment-<?=$j;?>"><?=$small_screenshot; ?></a></li>
	<? } ?>


<? } ?>
</ul>

<?php
for($i=0; $i<$this->numberOfRows;$i++) {

    $thumb = "";
    $guid = $this->data[$i][2];

    $rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($guid,'RELATED_IMAGE');
    $itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';
    
	$chkDir = $sDir."/".$guid."/".$itemGuid;
	
	if (@getimagesize($chkDir))
	{
	$pict = $sDir ."/". $guid ."/". $itemGuid;
	}
	else
	{
	$pict = $sDir ."/". $itemGuid;
	}
	
	
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) { $thumb = $pict . ".jpg"; }
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) { $thumb = $pict . ".gif"; }
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) { $thumb = $pict . ".png"; }

    if ($thumb == "") { $thumb = $this->cdn('images')."/nothumb.jpg"; }

    $screenshot = "<img src=\"".$thumb."\" alt=\"".$this->data[$i][0]."\" width=\"400\" height=\"250\" />";

	$j = $i+1; 

?>


		<? if ($j==1) { ?>
	    <div id="fragment-<?=$j;?>" class="ui-tabs-panel" style="">
			<?=$screenshot;?>		
			<div class="info">
				<h2><a href="<?=ROOT_URL;?>/berita/baca/<?=$guid;?>/<?=$this->data[$i][3];?>"><?=$this->data[$i][0];?></a></h2>
				<p><?=$this->data[$i][5];?>....<a href="#" >read more</a></p>
			</div>
	    </div>
	    <? } else { ?>
	    <div id="fragment-<?=$j;?>" class="ui-tabs-panel ui-tabs-hide" style="">
			<?=$screenshot;?>		
			<div class="info">
				<h2><a href="<?=ROOT_URL;?>/berita/baca/<?=$guid;?>/<?=$this->data[$i][3];?>"><?=$this->data[$i][0];?></a></h2>
				<p><?=$this->data[$i][5];?>....<a href="#" >read more</a></p>
			</div>
	    </div>
	    <? } ?>


<? } ?>
</div>

