<? if ($this->aData['totalCount'] != 0) { ?>
<table>
</table>
<br><div id='talksContent'></div><br>
<table>
        <tr>
                <td>&nbsp;</td>
                <td align="center"><div id='catalogPagination' class="pagination"></div></td>
        </tr>
</table>


<script>

$(document).ready(function(){

        var isFirstTime = 1;

        var myPageIndex = 0;

        $("#catalogPagination").pagination(<?=$this->aData['totalCount'];?>,
        {items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
        );

        function handlePaginationClick(new_page_index, pagination_container)
        {
                myPageIndex = new_page_index;
                myStart = (<?=$this->aData['limit'];?> * myPageIndex);

                if(true)
                {
                        if($('#tblCatalogPager-'+myPageIndex).length==0)
                        {
                                $.getJSON('<?=$this->baseUrl();?>/talks/widgets_catalog/detail/folderGuid/<?=$this->aData['folderGuid'];?>/start/'+myStart+'/limit/<?=$this->aData['limit'];?>', '', catalogResult);
                        }
                        else
                                showCatalogContent();
                }
                return false;
        }

        function catalogResult(res)
        {
                size = res.index.length;
                var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
                for(i=0;i<size;i++)
                {
                        tblRow +=

                                "<tr valign=top>"
                                +"<td>"
                                +"<h5>"+res.index[i].publish+"</h5>"
                                +"<div class='colgroup leading'>"+res.index[i].images
                                +"<div class='column' style='width:570px;'>"
                                +"<a href='<?=ROOT_URL;?>/berita/baca/"+res.index[i].guid+"/"+res.index[i].shortTitle+"'><b class='big'>"+res.index[i].title+"</b></a><br/>"
                                +"<p>"+res.index[i].desc+"</p>"
                                +"</div>"
                                +"</div>"
                                +"</td>"
                                +"</tr>";

                }
                tblRow += "</table>";
                $(tblRow).appendTo("#talksContent");
                showCatalogContent();
        }
        function showCatalogContent()
        {
                $('.tblCatalogPager').hide();
                $('#tblCatalogPager-'+myPageIndex).show();
                if(!isFirstTime)
                        Scroller.scroll();
                isFirstTime = 0;
        }


});



</script>
<? } ?>

