<div id="judul"><a href="<?=$this->baseUrl();?>"><img src="<?=$this->baseUrl();?>/resources/images/holid.jpg" alt="hukumonline" /></a></div>
<div class="align-left">
<small>Buat Akun HukumonlineID</small>
</div>
<div class="align-right">
    <a href="<?=ROOT_URL;?>">Halaman Depan</a> |
    <a href="<?=ROOT_URL;?>/identity/account/register">Daftar</a>
</div>
<div class="clear">&nbsp;</div>
<hr>
<section class="column first">
    <div class="colgroup leading">
        <div class="column width8 first">
            <h5><?=$this->title; ?></h5>
            <p><?=$this->content ?></p>
        </div>
    </div>
</section>
