<? if (count($this->aData) > 0) { ?>
<fieldset>
	<legend>SEJARAH</legend>
	<ul id="ppline">
	<? foreach ($this->aData as $data){?>
	<li>
		<? if($data['node']==$this->catalogGuid) {?>
		<img src="<?=$this->cdn('images'); ?>/page_right.gif">
		<? } ?>
			<a href="<?=$this->baseUrl();?>/pusatdata/detail/<?=$data['node'];?>/node/<?=$this->node; ?>"><?=$data['title']; ?></a><br>
			<?=$data['subTitle']; ?>
		<? if ($data['description']) { ?>
		<br><strong>Catatan: </strong><?=$data['description']; ?>
		<? } ?>
	</li>
	<? } ?>
	</ul>
</fieldset>
<? } ?>