<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="width8">

                <div id="panelRubrik">
                <div id="panelTitle">
                    <div id="panelTitleTitle"> isu hangat</div>
                    <div id="panelTitleIndex"></div>
                </div>
                <?=$this->action('indexwartawcom','widgets_content','berita',array('folderGuid'=>'lt4a6f7d5377193')); ?>
                </div>

            </div>
            <div class="clean">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->
