<div id="panelBeritaBawah">
<? if ($this->numberOfRows == 0) { ?>
<span style="font:11px verdana,arial,helvetica,sans-serif;">kosong</span>
<? } ?>
<ol>
	<? for($i=0; $i<$this->numberOfRows;$i++) { ?>
	<li id="panellistnoline">
		<div id="index_jam"><span class="jam">[<?=$this->data[$i][2]; ?>]</span></div>
		<div id="index_berita">
			<a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$this->data[$i][3]; ?>/<?=$this->data[$i][1]; ?>" class="linkhref"><?=$this->data[$i][0]; ?></a>
			<span style="font:11px verdana,arial,helvetica,sans-serif;color:#009933;"><?=$this->data[$i][4]; ?></span>
		</div>
	</li>
	<? } ?>
</ol>
</div>
