<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="width8">

                <div id="panelRubrik">
                <div id="panelTitle">
                    <div id="panelTitleTitle"> resensi</div>
                    <div id="panelTitleIndex"></div>
                </div>
                <?=$this->action('indexwarta','widgets_content','berita',array('folderGuid'=>'fb17')); ?>
                </div>

            </div>
            <div class="clean">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->
