<!-- S:TOP BAR -->
<div id="topholid" align="center"> 
    <div id="topcontent"> 
    <?=$this->action('miniprofile','index','hol-site');?>		
	<div class="search_hol"> 
    	<form action="<?=$this->getRemoteSearchUrl();?>/id/dms/search/result" method="get"  class="search-holsearch"> 
	        <input class="input" name="keyword" id="keyword" onblur="blur_text('masukkan kata kunci','keyword');" onfocus="focus_text('masukkan kata kunci','keyword');" value="masukkan kata kunci" type="text">
			<input type="submit" class="btun" value="" /> 
 	    </form> 
	</div> 
	<div class="social_icon">
		<span>Ikuti kami:</span> 
		<a href="http://rss.hukumonline.com" target="_blank"><img src="<?=$this->cdn('images');?>/feed.png" alt="feed rss" /></a>
		<a href="http://www.facebook.com/pages/Hukumonlinecom/101301323243289" target="_blank"><img src="<?=$this->cdn('images');?>/facebook.png" alt="facebook" /></a>
		<a href="http://twitter.com/#!/hukumonline" target="_blank"><img src="<?=$this->cdn('images');?>/twitterhol.png" alt="twitter" /></a>
	</div>
    </div> 
</div> 
<!-- E:TOP BANNER -->
<!-- S:Header -->
<header id="up">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="column width3 first">
                    <div id="judul"><a href="<?=ROOT_URL;?>"><img src="<?=$this->cdn('images');?>/logo_hukumonline.jpg" alt="hukumonline" /></a></div>
                </div>
                <div class="column width5">
                    <div class="topup">
                        <ul id="topnav">
                            <li><a href="http://en1.hukumonline.com" target="_blank">en.hukumonline.com</a></li>
                            <li><a href="http://hukumpedia.com" target="_blank">hukumpedia.com</a></li>
                            <li><a href="http://direktori.hukumonline.com" target="_blank">direktori.hukumonline.com</a></li>
                        </ul>
                    </div>
                    <div class="topdown">
                        <ul id="topnavi">
                            <li><a href="<?=$this->baseUrl();?>/faqs">Tentang Kami</a></li>
                            <li><a href="<?=$this->baseUrl();?>/faqs">Produk dan Jasa</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <div class="clean"></div>
        <div class="padding_top_10"></div>
        <nav style="width:100%;background:#00008B;">
        	<div class="align-left">
            	<?php 
            	$date = date('Y-m-d');
				$array_hari = array(1=>"Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu");
				$lang = array("Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "Nopember", "Desember");
				$hari = $array_hari[date("N",strtotime(date('Y-m-d H:i:s')))];
				$yy = substr($date, 0, 4);
				$mm = substr($date, 5, 2);
				$dd = substr($date, 8, 10);
				$today = $hari . ', '.$dd." ".$lang[$mm-1]." ".$yy;
				$time = date("H:i");
				?>
				<div style="vertical-align:middle;padding:8px;color:#fff;font:bold;">
					<?=$today;?> &raquo; <?=$time;?> WIB
				</div>
        	</div>
        	<div class="align-right">
	            <div id="menu">
				    <ul class="sf-menu">
				        <li><a href="<?=ROOT_URL;?>">Awal</a></li>
				        <li><a href="<?=ROOT_URL;?>/warta">Berita</a>
				        <? if ($this->menuFolder) : ?>
						<ul>
						
						    <?
						    for ($i=0;$i<count($this->menuFolder);$i++)
						    {
						    $json = new Zend_Json();
						    $aData = $json->decode($this->menuFolder[$i]['cmsParams']);
						    ?>
						    <li>
						    <a href="<?=ROOT_URL;?>/page/<?=$aData['st']?>"><?=$this->menuFolder[$i]['title']?></a>
						    <?=$this->action('getmenuchild','widgets_content','hol-site',array('node'=>$this->menuFolder[$i]['guid']))?>
						    </li>
						    <? } ?>
						
						</ul>
						<? endif; ?>
						</li>
				        <li><a href="<?=ROOT_URL;?>/pusatdata">Pusat Data</a></li>
				        <li><a href="<?=ROOT_URL;?>/klinik">Klinik</a>
				        <ul>
				            <? for($i=0; $i<$this->numberOfRows;$i++) { ?>
				                <li><a href="<?=ROOT_URL;?>/klinik/kategori/<?=$this->data[$i][1]; ?>" title="<?=$this->data[$i][0]; ?>"><?=$this->data[$i][0]; ?></a></li>
				            <? } ?>
				        </ul>
				        </li>
				        <li class="current"><a href="<?=ROOT_URL;?>/talks">Talks</a>
				        <ul>
				        	<li><a href="<?=ROOT_URL;?>/talks/events">Upcoming events</a></li>
				        </ul>
				        </li>                                                            
				        <li><a href="<?=ROOT_URL;?>/karir">Karir</a></li>
				        <li><a href="<?=ROOT_URL;?>/FAQ">FAQ</a></li>
				    </ul>
	            </div>
        	</div>
        </nav>
    </div>
</header>
<!-- E:Header -->
<div class="clean"></div>
<div class="margin_top_60"></div>