<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom first" style="width: 245px;padding-right:5px;">
                    <?=$this->action('miniprofile','index','hol-site');?>
                    <?=$this->action('viewcart','index','talks'); ?>
                    <div style="padding-top:5px;"></div>
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom" style="width: 723px;border-left: 1px solid #cecece; padding-left:10px;">
                	<div style="padding-top:20px"></div>
                    <?=$this->action('uevent','widgets_catalog','talks'); ?>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->