<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent_custom_6 first">
                    <?=$this->action('viewcart','index','talks'); ?>
                    <div class="padding_top_10"></div>
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
                    <?=$this->action('uevent','widgets_catalog','talks'); ?>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->