<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('kategori','widgets_content','klinik'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
                    <? $auth = Zend_Auth::getInstance();
                    if (!$auth->hasIdentity()) {
                    ?>
                    <br/><div id="judul2">Harap login terlebih dahulu</div>
                    <? } else { ?>
                    <?=$this->action('add-clinic','form','klinik'); ?>
                    <? } ?>
                    
                    <div class="padding_top_15"></div>
                    <?=$this->action('disclaimer','index','klinik'); ?>
                    <div class="padding_top_15"></div>
                    <?=$this->action('mitra-klinik','mitra','klinik'); ?>

                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->