<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('miniprofile','index','hol-site');?>
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom widthcontent5" style="border-left: 1px solid #cecece; padding-left: 5px;">
                    <h5>Hukumonline Polling</h5>
                    <hr>
                    <?=$this->action('detail','manager','polling',array('guid'=>$this->pollId)); ?>
                    <div style="padding-top:40px;"></div>
                    <?=$this->action('poll','manager','polling',array('guid'=>$this->pollId)); ?>
                    
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->

