<? if ($this->numberOfRows <> 0) { ?>
<div id="related">
    <div id="related_selip">
        <div id="berta">BERITA TERKAIT</div>
        <ul>
        <? foreach ($this->rowsetRelatedItem as $row) { ?>
        <li><a href="<?=$this->baseUrl(); ?>/berita/baca/<?=$row['itemGuid'] ?>/<?=$this->getCatalogShortTitle($row['itemGuid']) ?>"><?=$this->getCatalogTitle($row['itemGuid'],'fixedTitle'); ?></a></li>
        <? } ?>
        </ul>
    </div>
</div>
<div class="clean"></div>
<? } ?>