<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('kategori','widgets_content','klinik'); ?>
                    <div id="judul2" class="padding_top_10">Penjawab Lain</div>
                    <hr>
                    <?=$this->action('pengasuhlain','widgets_catalog','klinik',array('mitra'=>$this->partnerGuid,'guid'=>$this->catalogGuid)); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
                    <?=$this->action('detailmitra','widgets_catalog','klinik',array('guid'=>$this->partnerGuid)); ?>
                    <div class="padding_top_15"></div>
                    <?=$this->action('pengasuh','widgets_catalog','klinik',array('guid'=>$this->catalogGuid)); ?>
                    <div class="padding_top_15"></div>
                    <?//=$this->ajaxActionRenderer(ROOT_URL.'/klinik/mviewerklinikauthor/'.$this->catalogGuid);?>
                    <?=$this->action('vc','widgets_content','klinik',array('guid'=>$this->catalogGuid)); ?>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->