<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('kategori','widgets_content','klinik'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
                    <?=$this->action('rubrik','index','klinik'); ?><hr/>
                    <?=$this->ajaxActionRenderer(ROOT_URL.'/klinik/mkategoriklinik/'.$this->catalogGuid);?>
                    <hr>
                    <?=$this->action('disclaimer','index','klinik'); ?><br>
                    <?=$this->action('mitra-klinik','mitra','klinik'); ?>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->