<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('kategori','widgets_content','klinik'); ?>
                    <div id="judul2" class="padding_top_10">Kategori: <?=$this->getClinicCategory($this->catalogGuid);?></div>
                    <hr/>
                    <?=$this->ajaxActionRenderer(ROOT_URL.'/klinik/mkategori/'.$this->catalogGuid);?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
					<?=$this->action('rubrik','index','klinik'); ?><hr/>
                    <?=$this->action('klide','widgets_catalog','klinik',array('guid'=>$this->catalogGuid)); ?>
                    <hr>
                    <?=$this->action('disclaimer','index','klinik'); ?><br>
                    <?=$this->action('mitra-klinik','mitra','klinik'); ?>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->