<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10 padding_top_20">
                    <?=$this->action('detail','widgets_catalog','hol-site',array('guid'=>$this->catalogGuid,'page'=>$this->page)); ?>
                    <?=$this->action('beritaterkait','widgets_relation','hol-site',array('guid'=>$this->catalogGuid)); ?>
                    <?=$this->action('browse','manager','comment',array('guid'=>$this->catalogGuid)); ?>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<div class="clear">&nbsp;</div>
<!-- End of Page Content -->