<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom first" style="border-right: 1px solid #cecece; width: 245px;padding-right:5px;">
                    <?=$this->action('miniprofile','index','hol-site');?>
                    <?=$this->action('terbaru','widgets_sidebar','hol-site'); ?>
                </div>
                <div class="kolom widthcontent5" style="padding-left: 5px;">
                    <div class="box box-error">Error</div>
                    <div class="box box-error-msg">
                        <ol>
                            <li>We are sorry. No order found.</li>
                        </ol>
                    </div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->