<? if ($this->aData['totalCount'] != 0) { ?>
<div id='catalogContent'></div><br>
<table>
	<tr>
		<td>&nbsp;</td>
		<td align="center"><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>


<script>

$(document).ready(function(){

	var isFirstTime = 1;

	var myPageIndex = 0;

	$("#catalogPagination").pagination(<?=$this->aData['totalCount'];?>,
	{items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
	);

	function handlePaginationClick(new_page_index, pagination_container)
	{
		myPageIndex = new_page_index;
		myStart = (<?=$this->aData['limit'];?> * myPageIndex);

		if(true)
		{
			if($('#tblCatalogPager-'+myPageIndex).length==0)
			{
				$('#message_box').show();
				$.getJSON('<?=$this->baseUrl();?>/klinik/kontributorklinik/<?=$this->aData['catalogGuid'];?>/'+myStart+'/<?=$this->aData['limit'];?>', '', klinikResult);
			}
			else
				showCatalogContent();
		}
		return false;
	}

	function klinikResult(res)
	{
		size = res.klinikkategori.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow +=

                "<tr valign=top>"
                +"<td>"
                +"<div class='klinikterbaruisi'>"
                +"<div style='float:left;padding:2px;margin: 1px 10px 10px 0px;'><a href=''>"+res.klinikkategori[i].img+"</a></div>"
                +"<div style='float:right;width:585px;'>"
                +"<div id='kcss'>"
                +"<a href='<?=ROOT_URL; ?>/klinik/detail/"+res.klinikkategori[i].guid+"'>"+res.klinikkategori[i].title+"</a>"
                +"</div>"
                +"<small>Di <a href='<?=ROOT_URL;?>/klinik/kategori/"+res.klinikkategori[i].kategoriklinik+"' class='subtitle'>"+res.klinikkategori[i].kategori+"</a> - Ditanyakan oleh "+res.klinikkategori[i].createdBy+" - Jawaban Oleh <a href='<?=ROOT_URL;?>/klinik/penjawab/"+res.klinikkategori[i].kontributor+"/mitra/"+res.klinikkategori[i].source+"' class='subtitle'>"+res.klinikkategori[i].author+"</a> - "+res.klinikkategori[i].pd+"</small>"
                +"</div>"
                +"<div class='clean'></div>"
                +"</div>"
                +"</td>"
                +"</tr>";

		}
		tblRow += "</table>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
		$('#message_box').fadeOut();
	}
	function showCatalogContent()
	{
		$('.tblCatalogPager').hide();
		$('#tblCatalogPager-'+myPageIndex).show();
		if(!isFirstTime)
			Scroller.scroll();
		isFirstTime = 0;
	}


});



</script>
<? } else { ?>
<span style="font:12px verdana,arial,helvetica,sans-serif;">Klinik kosong</span>
<? } ?>