<div id="judul2">KATEGORI: <?=$this->getCatalogAttribute($this->aData['catalogGuid'],'fixedTitle');?></div>
<? if ($this->aData['totalCount'] != 0) { ?>
<div id='klinik_box'></div>
<div id='catalogContent'></div><br>
<table>
	<tr>
		<td>&nbsp;</td>
		<td align="center"><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>


<script>

$(document).ready(function(){

	var isFirstTime = 1;

	var myPageIndex = 0;

	$("#catalogPagination").pagination(<?=$this->aData['totalCount'];?>,
	{items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
	);

	function handlePaginationClick(new_page_index, pagination_container)
	{
		myPageIndex = new_page_index;
		myStart = (<?=$this->aData['limit'];?> * myPageIndex);

		if(true)
		{
			if($('#tblCatalogPager-'+myPageIndex).length==0)
			{
				$('#klinik_box').fadeOut('slow').append('<p id="loading">&nbsp;</p>');
				$.getJSON('<?=$this->baseUrl();?>/klinik/kategoriklinik/<?=$this->aData['catalogGuid'];?>/'+myStart+'/<?=$this->aData['limit'];?>', '', klinikResult);
			}
			else
				showCatalogContent();
		}
		return false;
	}

	function klinikResult(res)
	{
		size = res.klinikkategori.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow +=

                        "<tr valign=top>"
                        +"<td>"
                        +"<div class='klinikterbaruisi'>"
                        +res.klinikkategori[i].existence
                        +"<div style='float:right;width:661px;'>"
                        +"<div id='kcss'>"
                        +"<a href='<?=ROOT_URL;?>/klinik/detail/"+res.klinikkategori[i].guid+"'>"+res.klinikkategori[i].title+"</a>"
                        +"</div>"
                        +"<small>Ditanyakan oleh "+res.klinikkategori[i].createdBy+" - Jawaban Oleh <a href='<?=ROOT_URL;?>/klinik/penjawab/"+res.klinikkategori[i].author+"/mitra/"+res.klinikkategori[i].sid+"' class='subtitle'>"+res.klinikkategori[i].source+"</a> - "+res.klinikkategori[i].publishedDate+"</small>"
                        +"</div>"
                        +"<div class='clean'></div>"
                        +"</div>"
                        +"</td>"
                        +"</tr>";


		}
		tblRow += "</table>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
		$('#klinik_box').fadeOut('slow');
	}
	function showCatalogContent()
	{
		$('.tblCatalogPager').hide();
		$('#tblCatalogPager-'+myPageIndex).show();
		
		if(!isFirstTime)
			Scroller.scroll();
			
		isFirstTime = 0;
	}


});



</script>
<? } else { ?>
<span style="font:12px verdana,arial,helvetica,sans-serif;">Kategori klinik kosong</span>
<? } ?>