<? if ($this->aData['totalCount'] != 0) { ?>
<div id='catalogContent'></div><br>
<table>
	<tr>
		<td width=25%>&nbsp;</td>
		<td align="center"><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>


<script>

$(document).ready(function(){

	var isFirstTime = 1;

	var myPageIndex = 0;

	$("#catalogPagination").pagination(<?=$this->aData['totalCount'];?>,
	{items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
	);

	function handlePaginationClick(new_page_index, pagination_container)
	{
		myPageIndex = new_page_index;
		myStart = (<?=$this->aData['limit'];?> * myPageIndex);

		if(true)
		{
			if($('#tblCatalogPager-'+myPageIndex).length==0)
			{
				$('#message_box').show();
				$.getJSON('<?=$this->baseUrl();?>/klinik/kategoriklinik/<?=$this->aData['catalogGuid'];?>/'+myStart+'/<?=$this->aData['limit'];?>', '', klinikResult);
			}
			else
				showCatalogContent();
		}
		return false;
	}

	function klinikResult(res)
	{
		size = res.klinikkategori.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow +=

				"<tr valign=top>"
				+"<td><span class='subtitle'>[<b>"+res.klinikkategori[i].kategori+"</b>]</span>&nbsp;<a href='<?=$this->baseUrl(); ?>/klinik/detail/"+res.klinikkategori[i].guid+"' class='klinikbrowse'><b>"+res.klinikkategori[i].title+"</b></a><br/>"
				+"<span class='subtitle'>Pertanyaan :</span>"
				+"<p>"+res.klinikkategori[i].pertanyaan+"</p>"
				+"<p><small>"
                                +"Penanya: "+res.klinikkategori[i].createdBy+"<br>"
				+"Jawaban oleh: "+res.klinikkategori[i].author+"<br>"
				+"Sumber: "+res.klinikkategori[i].sumber+"<br>"
				+"</small></p><div style='padding-top:5px;'></div>"
				+"</td>"
				+"</tr>";

		}
		tblRow += "</table>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
		$('#message_box').fadeOut();
	}
	function showCatalogContent()
	{
		$('.tblCatalogPager').hide();
		$('#tblCatalogPager-'+myPageIndex).show();
		if(!isFirstTime)
			Scroller.scroll();
		isFirstTime = 0;
	}


});



</script>
<? } else { ?>
<span style="font:12px verdana,arial,helvetica,sans-serif;">Kategori klinik kosong</span>
<? } ?>