<br/>
<div class="votitaly-inline-rating" id="votitaly-inline-rating-1">
    <span class="votitaly-get-id" style="display:none;">1</span>

    <span class="votitaly-inline-rating">
    <ul class="votitaly-star-rating">
            <li class="current-rating" id="current-rating-<?=$this->catalogGuid; ?>"><!-- will show current rating --></li>
            <span id="ratelinks">
            <li><a href="javascript:void(0)" title="1 star out of 5" class="one-star">1</a></li>
            <li><a href="javascript:void(0)" title="2 stars out of 5" class="two-stars">2</a></li>
            <li><a href="javascript:void(0)" title="3 stars out of 5" class="three-stars">3</a></li>
            <li><a href="javascript:void(0)" title="4 stars out of 5" class="four-stars">4</a></li>
            <li><a href="javascript:void(0)" title="5 stars out of 5" class="five-stars">5</a></li>
            </span>
    </ul>
    </span>

    <div class="votitaly-box">
    <?=$this->drawrating; ?>
    </div>

</div>

<div style="float:right;z-index:1;overflow:hidden;">
    
    <!-- AddThis Button BEGIN -->
    <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
    <div class="addthis_toolbox addthis_default_style">
    <a class="addthis_button_facebook"></a>
    <a class="addthis_button_google"></a>
    <a class="addthis_button_twitter"></a>
    <a class="addthis_button_email"></a>
    <a class="addthis_button_favorites"></a>
    <span class="addthis_separator">|</span>
    <a href="http://www.addthis.com/bookmark.php?v=250&amp;username=hukumonline" class="addthis_button_expanded">More</a>
    </div>
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=hukumonline"></script>
    <!-- AddThis Button END -->

</div>
<div class="padding_top_10"></div>
<div class="clean"></div>
<?
    $arraypictureformat = array("jpg", "jpeg", "gif");
    $txt_allowedformat = implode('; ', $arraypictureformat);
    $registry = Zend_Registry::getInstance();
    $config = $registry->get(Pandamp_Keys::REGISTRY_APP_OBJECT);
    $cdn = $config->getOption('cdn');
    
    $sDir = $cdn['static']['dir']['photo'];
    $sDir2 = $cdn['static']['url']['photo'].'/';
    
    $modelUser = App_Model_Show_User::show()->getUserByName($this->createdBy);
    
    $x = 0;
    foreach ($arraypictureformat as $key => $val) {
        if (is_file($sDir."/".$modelUser['kopel'].".".$val)) {
            $myphoto = $sDir."/".$modelUser['kopel'].".".$val;
            $myext = $val;
            $x = 1;
            break;
        }
    }
    if ($x == 1) {
        $myphotosize = getimagesize($myphoto);
        $dis = "";
        if (isset($myext) && is_file($sDir."/".$modelUser['kopel'].".".$myext))
            $txt_existence = "<img src=\"".$sDir2.$modelUser['kopel'].".".$myext."\" class=\"avatar\" width=\"58\" height=\"58\" />";

    }
    else
    {
        $txt_existence = "<img src=\"".$this->cdn('images')."/gravatar-140.png\" width=\"58\" height=\"58\" class=\"avatar\" border=\"0\" />";
    }
?>


<div style="width:74px;float:left;padding:2px;margin:1px 10px 10px 0;text-align:center;display:inline;">
	<a href=""><?=$txt_existence;?></a><br>
	<div class="ta-center" style="width:60px;overflow:auto;"><a href="" title="<?=$this->createdBy;?>" class="klinikbrowse"><?=$this->createdBy;?></a></div>
</div>
<div style="float:right;width:645px;">
	<div id="judul2">
	<b><?=$this->title;?></b>
	</div>
	<div class="cliniccontent"><?=$this->question;?></div>
	<small>Di <a href="<?=ROOT_URL;?>/klinik/kategori/<?=$this->category;?>" class="subtitle"><?=$this->getCatalogAttribute($this->category,'fixedTitle');?></a></small>
</div>
<div class="clean"></div>
<div class="padding_top_20"></div>
<div class="bor"></div>
<div class="padding_top_20"></div>

<?
    $modelUser = App_Model_Show_User::show()->getUserByName($this->getCatalogAttribute($this->author,'fixedTitle'));
    
    $x = 0;
    foreach ($arraypictureformat as $key => $val) {
        if (is_file($sDir."/".$modelUser['kopel'].".".$val)) {
            $myphoto = $sDir."/".$modelUser['kopel'].".".$val;
            $myext = $val;
            $x = 1;
            break;
        }
    }
    if ($x == 1) {
        $myphotosize = getimagesize($myphoto);
        $dis = "";
        if (isset($myext) && is_file($sDir."/".$modelUser['kopel'].".".$myext))
            $txt_existence = "<img src=\"".$sDir2.$modelUser['kopel'].".".$myext."\" class=\"avatar\" width=\"58\" height=\"58\" />";

    }
    else
    {
        $txt_existence = "<img src=\"".$this->cdn('images')."/gravatar-140.png\" width=\"58\" height=\"58\" class=\"avatar\" border=\"0\" />";
    }
?>
<div id="judul2">
<b>Jawaban</b>
</div>
<div class="ta-left"><a href="<?=ROOT_URL;?>/klinik/mitra/<?=$this->source;?>" title="<?=$this->getCatalogAttribute($this->source,'fixedTitle');?>" target="_blank" class="klinikbrowse"><?=$this->getCatalogAttribute($this->source,'fixedTitle');?></a></div>
<div style="float:left;padding:2px;margin:15px 10px 10px 0;">
	<a href=""><?=$txt_existence;?></a>
</div>
<div style="float:right;width:651px;">
	<div class="cliniccontent"><?=$this->answer;?></div>
	<small>
	<a href="<?=ROOT_URL;?>/klinik/penjawab/<?=$this->author;?>/mitra/<?=$this->source;?>" title="<?=$this->getCatalogAttribute($this->author,'fixedTitle');?>" target="_blank" class="klinikbrowse"><?=$this->getCatalogAttribute($this->author,'fixedTitle');?></a><br>
	<?=$this->publishedDate;?>
	</small>
</div>
<div class="clean"></div>
<div class="padding_top_20"></div>
<div class="bor"></div>

<div class="padding_top_5"></div>
<?=$this->action('beritaterkait','widgets_relation','klinik',array('guid'=>$this->catalogGuid)); ?>
<div class="padding_top_5"></div>
<?=$this->action('dasarhukum','widgets_relation','klinik',array('guid'=>$this->catalogGuid)); ?>
<div class="clean"></div>

