<? if ($this->numberOfRows == 0) { ?>
<span style="font:12px verdana,arial,helvetica,sans-serif;">Tidak ada klinik</span>
<? } ?>
<div class="klinikterbaruisi">
<? for ($i=0;$i<$this->numberOfRows;$i++) { ?>
<span class="subtitle">[<b><?=$this->data[$i][2];?></b>]</span>&nbsp;<a href="<?=$this->baseUrl(); ?>/klinik/detail/<?=$this->data[$i][3];?>" class="klinikbrowse"><?=$this->data[$i][0];?></a>
<p><?=$this->data[$i][1];?></p>
<p>
    <div class="author">Penanya: <?=$this->data[$i][4];?></div>
</p>
<? } ?>
</div>
