<div id="isiberita">
<span class="subtitle"><?=$this->date; ?></span>
<? if ($this->subtitle) { ?><div class="subjudul"><?=$this->subtitle; ?></div><? } ?>
<div id="judul3"><?=$this->title; ?></div>
<? if ($this->description) { ?>
<q><?=$this->description; ?></q>
<? } ?>
<span class="reporter"><abbr><?=$this->author;?></abbr></span>
<div class="socialshare">
<ul>
	<li class="share">Share:</li>
	<li class="share"><iframe src="http://www.facebook.com/plugins/like.php?href=<?= urlencode('http://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']) ?>&layout=standard&show_faces=false&width=450&action=like&colorscheme=light" scrolling="no" frameborder="0" allowTransparency="true" style="border:none; overflow:hidden; width:320px; height:30px"></iframe></li>
	<li class="share"><a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="hukumonline">Tweet</a></li>
	<li class="share"><g:plusone></g:plusone></li>
</ul>
</div>
<div class="clean"></div>
<div class="busear">
    <a href="javascript:;" title="PDF" onclick="javascript:printPdf('<?=$this->catalogGuid?>')" rel="nofollow"><img src="<?=$this->cdn('images'); ?>/pdf_button.png" alt="PDF"></a>&nbsp;
    <a href="javascript:;" title="Print" onclick="javascript:printEDoc('<?=$this->catalogGuid?>')" rel="nofollow"><img src="<?=$this->cdn('images'); ?>/printButton.png" alt="Print"></a>&nbsp;
    <a href="javascript:;" title="E-mail" onclick="javascript:sendEMail('<?=$this->catalogGuid?>')"><img src="<?=$this->cdn('images'); ?>/emailButton.png" alt="E-mail"></a>
</div>
<div class="clean"></div>
<?
$sDir = $this->getRemoteImageUrl();
$thumb = "";

$rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getDocumentById($this->catalogGuid,'RELATED_IMAGE');
$itemGuid = (isset($rowsetRelatedItem['itemGuid']))? $rowsetRelatedItem['itemGuid'] : '';
$chkDir = $sDir."/".$this->catalogGuid."/".$itemGuid;
if (@getimagesize($chkDir))
{
	$pict = $sDir ."/". $this->catalogGuid ."/". $itemGuid;
}
else 
{
	$pict = $sDir ."/". $itemGuid;
}

if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) 	{ $thumb = $pict . ".jpg"; 	}
if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) 	{ $thumb = $pict . ".gif"; 	}
if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) 	{ $thumb = $pict . ".png"; 	}


$screenshot = "<img src=\"".$thumb."\" />";

list($width) = getimagesize($thumb); 
?>

<? if (!empty($thumb)) : ?>
<div class="sketsa"><?=$screenshot; ?><br>
	<div style="width:<?=$width;?>px;overflow:auto;">
    <caption>
        <strong><?=$this->getFotoAttributeName($rowsetRelatedItem['itemGuid']); ?></strong>
    </caption>
    </div>
</div>
<? endif; ?>
<?=$this->content;?><br>
<span class="code">Dibaca : <?=$this->numOfClick; ?></span>

</div>