<span class="subtitle"><?=$this->date; ?> WIB</span>
<div class="beritaFotoJD">beritaFoto</div>
<? if ($this->subtitle) { ?><span class="subjudul"><?=$this->subtitle; ?></span><? } ?>
<div id="judul2"><?=$this->title; ?></div>
<div style="font-family: arial,helvetica,sans-serif;font-size: 14px;line-height: 1.5em;">
Pewarta Photo : <?=$this->author; ?>
</div>
<div id="products_example">
<div id="products">
	<div class="slides_container">
	<?php
    $sDir = $this->getRemoteImageUrl();
    $thumb = "";

	$rowsetRelatedItem = App_Model_Show_RelatedItem::show()->getAllDocumentById($this->catalogGuid,'RELATED_IMAGE');
	if ($rowsetRelatedItem) {
		foreach ($rowsetRelatedItem as $rri)
		{
			$chkDir = $sDir."/".$rri['relatedGuid']."/".$rri['itemGuid'];
			if (@getimagesize($chkDir))
			{
				$pict = $sDir."/".$rri['relatedGuid']."/".$rri['itemGuid'];
			}
			else 
			{
				$pict = $sDir ."/". $rri['itemGuid'];
			}
			
		
			if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) 	{ $thumb = $pict . ".jpg"; 	}
			if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) 	{ $thumb = $pict . ".gif"; 	}
			if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) 	{ $thumb = $pict . ".png"; 	}
			
			$screenshot = "<img src=\"".$thumb."\" alt=\"".$rri['itemGuid']."\" width=\"606\" height=\"424\" />";
	?>
	
		<div>
		<?=$screenshot;?>
		<div class="caption"><?=$this->getFotoAttributeName($rri['itemGuid']);?></div>
		</div>
		
	<?	} ?>

	</div>
	<div style="clear:both;padding-top:20px;"></div>
	<div class="fl">
	<div class="fo">Foto Lain :</div>
	<ul class="pagination">
	<?
		foreach ($rowsetRelatedItem as $rri)
		{
			$chkDir = $sDir."/".$rri['relatedGuid']."/".$rri['itemGuid'];
			if (@getimagesize($chkDir))
			{
				$pict = $sDir."/".$rri['relatedGuid']."/".$rri['itemGuid'];
			}
			else 
			{
				$pict = $sDir ."/". $rri['itemGuid'];
			}
			
		
			if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) 	{ $thumb = $pict . ".jpg"; 	}
			if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) 	{ $thumb = $pict . ".gif"; 	}
			if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) 	{ $thumb = $pict . ".png"; 	}
			
			$screenshot = "<img src=\"".$thumb."\" alt=\"".$rri['itemGuid']."\" width=\"99px\" height=\"71px\" />";
	?>
	
		<li><a href="#"><?=$screenshot;?></a></li>
		
	<?	} ?>

	</ul>
	</div>
	
	<?
	} 
	?>
</div>
<div class="clean"></div>
</div>

