<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    	<? $title = ($this->catalogGuid)? ' : '.$this->getCatalogAttribute($this->catalogGuid,'fixedCommentTitle') : ''; ?>
        <title>hukumonline.com - Klinik <?=str_replace(": No-Title","",$title);?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?
		if($this->catalogGuid!="")
		{
		?>
		<meta property="og:title" content="<?=$title2;?>" />
		<?
		}
		?>
        <meta name="google-site-verification" content="MUDP2J4JyyfKSWJsjfuglidOXiHOU_vn5VLXY7S-G8w" />
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/typography.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/style.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?=$this->cdn('styles')?>/pagination.css" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/jquery/ui/jquery.ui.core.min.js,hol/jquery/ui/jquery.ui.widget.min.js,hol/jquery/ui/jquery.ui.tabs.min.js,hol/jquery/tooltip/jquery.tipTip.min.js,hol/jquery/form/jquery.validate.pack.js,hol/jquery/paging/jquery.pagination.js,hol/jquery/newsticker/jquery.newsticker.pack.js,hol/smooth.scroller.js" ></script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->
        
        <style>
		Html, body {
			Overflow-x:hidden;
		}
		</style>


        <script type="text/javascript">
            jQuery(document).ready(function()
            {
                Administry.setup();
                
                jQuery("#container-1").tabs();

                jQuery("#news").newsTicker();

            });

			var gid = function(x) { return document.getElementById(x); };
			function focus_text(msg, id){
			    if(gid(id).value == msg){
			        gid(id).value="";
			    }
			}
			function blur_text(msg, id){
			    if(gid(id).value.length < 1){
			        gid(id).value=msg;
			    }
			}
			
        </script>

    </head>
    <body>
        <?=$this->render('header.phtml');?>
        <?=$this->layout()->content;?>
        <?=$this->render('footer.phtml');?>

	<!-- Scroll to top link -->
	<a style="display: none;" id="totop">^ scroll to top</a>
	
        <script type="text/javascript" src="<?=$this->cdn('scripts');?>/hol/administry.js"></script>
		<script type="text/javascript">
		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
		</script>
		<script type="text/javascript">
		try{
		var pageTracker = _gat._getTracker("UA-24894495-1");
		pageTracker._trackPageview();
		} catch(err) {}
		</script>        
		
    </body>
</html>