<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com Cetak PDF</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
    <link href="<?=$this->cdn('styles')?>/printpdf.css" media="screen, projection" rel="stylesheet" type="text/css" />
</head>
<body>
	<?=$this->layout()->content; ?>
	<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	</script>
	<script type="text/javascript">
	try{
	var pageTracker = _gat._getTracker("UA-24894495-1");
	pageTracker._trackPageview();
	} catch(err) {}
	</script>        
	
</body>
</html>