<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="google-site-verification" content="MUDP2J4JyyfKSWJsjfuglidOXiHOU_vn5VLXY7S-G8w" />
        <title>hukumonline.com : <?=$this->identity;?></title>
        <link href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->baseUrl();?>/resources/css/typography.css" media="screen" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="<?=$this->baseUrl();?>/js/jquery/form/jquery.validate.pack.js"></script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/ie.css"/>

        <script src="<?=$this->baseUrl();?>/js/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->baseUrl();?>/js/IE8.js"></script>

        <![endif]-->

        <style type="text/css">
            div.cc { background-color: #eee; border: 1px solid red; }
            div.cc ol li { list-style:none }
            div.cc { display: none; }
            .cc label.error { display: inline; }
        </style>

    </head>
    <body>
        <div id="page">
            <div class="wrapper">
                <?=$this->layout()->content;?>
            </div>
        </div>
    </body>
</html>