<? if ((count($this->aPath)-1) > 0) { ?>
<ul class="breadcrumbs ta-right">
<? for($i=0; $i<count($this->aPath);$i++) { ?>
	<? if($i != count($this->aPath)-1) {?>
            <li><a href="<?=$this->aPath[$i]['url']; ?>"><span class="<?=($i%2 ? 'label label-blue' : 'label label-red');?>"><b><?=$this->aPath[$i]['title'];?></b></span></a></li>
	<? } else {?>
            <li><a href="<?=$this->aPath[$i]['url']; ?>"><b><?=$this->aPath[$i]['title'];?></b></a></li>
	<? } ?>

<? } ?>
</ul>
<? } ?>