<?php if (!$this->rows) { ?>
<div id="blokIsiKomen">
	Belum ada tanggapan untuk ditampilkan pada artikel ini.
</div>
<?php } else { ?>
<div id="comments">
<div id="blokIsiKomen">
	<b>Komentar terkini (<?php echo $this->numrows; ?> Komentar)</b>
</div>
<?php foreach ($this->paginator as $comment) : ?>
	<div id="blokIsiKomen">
		<div class="comment-avatar">
		<?php
			$arraypictureformat = array("jpg", "jpeg", "gif");
			//$sDir = ROOT_DIR.DIRECTORY_SEPARATOR.'uploads'.DIRECTORY_SEPARATOR.'photo';
			//$sDir2 = ROOT_URL."/uploads/photo/";
			$sDir = $this->getRemotePhotoDir();
			$sDir2 = $this->getRemotePhotoUrl();
			$x = 0;
			foreach ($arraypictureformat as $key => $val) {
				if (is_file($sDir."/".$comment['userid'].".".$val)) {
					$myphoto = $sDir."/".$comment['userid'].".".$val;
					$myext = $val;
					$x = 1;
					break;
				}
			}
			if ($x == 1) {
				$myphotosize = getimagesize($myphoto);
				$dis = "";
				if (isset($myext) && is_file($sDir."/".$comment['userid'].".".$myext))
					$txt_existence = "<img src=\"".$sDir2.$comment['userid'].".".$myext."\" width=\"52\" height=\"52\" />";

			}
			else
			{
				$txt_existence = "<img src=\"".$this->cdn('images')."/gravatar-140.png\" border=\"0\" />";
			}

			echo $txt_existence;
		?>

		</div>
		<div class="comment-box">
			<div class="avatar-indent">
				<span class="comment-title"><?=$comment['title'];?></span> &mdash;
				<span class="comment-author"><?=$comment['name'];?></span>
				<span class="comment-date"><?=Pandamp_Lib_Formater::get_date($comment['date']);?></span>
				<div class="comment-body"><?=Pandamp_Lib_Bbcode::parseBBCode($comment['comment']); ?></div>
				<div class="togglereplychild">
					<? if ($this->getNumOfComment($comment['id']) != 0) { ?>
					<a href="#" class="togglechild"><?=$this->getNumOfComment($comment['id']); ?></a>&nbsp;&nbsp;|&nbsp;&nbsp;
					<? } ?>
					<a href="#comment-<?=$comment['id'];?>" id="reply-<?=$comment['id'];?>" class="togglereply" onclick="return false">Balas Tanggapan</a>
				</div>
				<? if ($this->getNumOfComment($comment['id']) != 0) { ?>
				<div class="childcomments">
					<?
					$i=0;
					foreach ($this->getComment($comment['id']) as $child) {
					?>
					<div id="comment-<?=$child['id']; ?>" class="<?=($i%2 ? 'commentdetails-child2' : 'commentdetails-child'); ?>">
						<div class="comment-avatar">
						<?
						$x = 0;
						foreach ($arraypictureformat as $key => $val) {
							if (is_file($sDir."/".$child['userid'].".".$val)) {
								$myphoto = $sDir."/".$child['userid'].".".$val;
								$myext = $val;
								$x = 1;
								break;
							}
						}
						if ($x == 1) {
							$myphotosize = getimagesize($myphoto);
							$dis = "";
							if (isset($myext) && is_file($sDir."/".$child['userid'].".".$myext))
								$txt_existence = "<img src=\"".$sDir2.$child['userid'].".".$myext."\" width=\"52\" height=\"52\" />";

						}
						else
						{
							$txt_existence = "<img src=\"".$this->cdn('images')."/gravatar-140.png\" border=\"0\" />";
						}

						echo $txt_existence;

						?>
						</div>
						<div class="comment-box">
							<div class="avatar-indent">
								<span class="comment-title"><?=$child['title'];?></span> &mdash;
								<span class="comment-author"><?=$child['name'];?></span>
								<span class="comment-date"><?=Pandamp_Lib_Formater::get_date($child['date']);?></span>
								<div class="comment-body"><?=Pandamp_Lib_Bbcode::parseBBCode($child['comment']); ?></div>
							</div>
						</div>
					</div>
					<?
					$i++;
					}
					?>
				</div>
				<? } ?>
			</div>
		</div>
		<div id="divClear"></div>
	</div>
<?php endforeach; ?>
</div>
<?php if (count($this->rows) > 10) { ?>
<div class="copage">
		<b>Halaman: </b>
		<?php
			/*
			 * Print the pagination of type
			 */
			echo $this->paginationControl($this->paginator,
		                                    'Sliding',
		                                    '/partials/user_pagination_control.phtml'); ?>	 dari total <b><?php echo count($this->paginator); ?></b> halaman

</div>
<?php }} ?>