<h3>Klinik Hukumonline</h3>
<div id="container-1">
    <ul>
        <li><a class="corner-tl" href="#tabs-1">Terbaru</a></li>
        <li><a class="" href="#tabs-2">Terpopuler</a></li>
        <li><a class="" href="#tabs-3">Bundel</a></li>
        <li><a class="" href="#tabs-4">Terpilih</a></li>
    </ul>
    <div id="tabs-1">
        <?=$this->action('terbaru','widgets_content','klinik'); ?>
    </div>
    <div id="tabs-2">
        <?=$this->action('popular','widgets_content','klinik'); ?>
    </div>
    <div id="tabs-3">
	    bundel
    </div>
    <div id="tabs-4">
	    terpilih
    </div>
</div>
