<div class="box">
    <h5>Disclaimer</h5>
    <ul>
        <li>Seluruh informasi dan data yang disediakan dalam Klinik hukumonline.com adalah bersifat umum dan disediakan untuk tujuan pendidikan saja. Dengan demikian tidak dianggap sebagai suatu nasehat hukum.</li>
        <li>Pada dasarnya Klinik hukumonline.com tidak menyediakan informasi yang bersifat rahasia dan hubungan klien - penasehat hukum tidak terjadi. Untuk suatu nasehat hukum yang dapat diterapkan pada kasus yang Anda hadapi, Anda dapat menghubungi seorang penasehat hukum yang berpotensi.</li>
        <li>Klinik hukumonline.com berhak sepenuhnya mengubah judul dan/atau isi pertanyaan tanpa mengubah substansi dari hal-hal yang ditanyakan.</li>
    </ul>
</div>
