<fieldset>
    <legend>RUBRIK KLINIK</legend>
    <p>
        Rubrik ini disediakan bagi anda untuk mengajukan persoalan hukum yang anda hadapi. Rubrik ini diperuntukkan hanya kepada member Hukumonline.com.
    </p>
    <p>
    <a id="pertanyaan" href="<?=$this->baseUrl();?>/klinik/form" style="font-family: arial;font-size: 8pt;color: #000000;text-decoration: none;"><img src="<?=$this->cdn('images'); ?>/icon_pertanyaan.gif" border="0"></a>
    </p>
    <form id="searchKlinik" method="POST" action="<?=$this->baseUrl();?>/klinik/search">
        <p>
            <label for="cp" style="padding-right:13px;">Cari jawaban:</label>
            <input type="text" id="searchQuery" name="searchQuery" size="21" value='<?=$this->layout()->searchQuery;?>' style="width:255px;">
        </p>
        <p>
            <div style="padding-left:7.8em;font-size:14px;">
            <?=Pandamp_Lib_Form::categoryClinicPullDown($this->layout()->categorySearchQuery); ?>
            </div>
        </p>
        <p>
            <div style="padding-left:7.8em;font-size:14px;z-index:1;overflow:hidden;">
            <input type="submit" value="Telusuri" name="B3" class="btn btn-blue">
            </div>
        </p>
    </form>
</fieldset>