<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="kolom widthcontent1 first">
                    <?=$this->action('kategori','widgets_content','klinik'); ?>
                </div>
                <div class="kolom widthcontent6 bl_grey padding_left_10">
                    <?=$this->action('detailmitra','widgets_catalog','klinik',array('guid'=>$this->catalogGuid)); ?>
                    <div class="padding_top_15"></div>
                    <hr/>
                    <?=$this->ajaxActionRenderer(ROOT_URL.'/klinik/mklinikcontributor/'.$this->catalogGuid);?>
					<br>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page Content -->