<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
            <div class="colgroup">
                <div class="column width8 first">
                	<div class="ta-center">
                		<div id="judul3">Keamanan Situs</div>
                		<h4>Hukumonline telah menerapkan sejumlah level keamanan guna menjaga keutuhan situs ini, kami minta maaf
                		jika anda mengalami ketidaknyamanan dalam mengakses situs kami. Untuk lebih lanjut harap agar dibersihkan
                		cookies yang ada pada browser anda. Terima Kasih</h4>
                	</div>
                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</div>
<!-- End of Page content -->
