<!-- Page footer -->
<footer id="down">
    <div class="wrapper">
            <section class="column width8 first">
                <div class="colgroup leading">
                <div class="column width2 first">
                    <div id="title" style="margin:55px 20px"><img src="<?=$this->cdn('images');?>/logo_footer.gif" alt="hukumonline" /><!--<span>Footer Hukumonline</span>--></div>
                </div>
                <div class="column width5" style="padding-top:35px;padding-left:5px;">
                    <div class="footerMenu">
                        <ul>
                            <li><a href="<?=ROOT_URL;?>">Awal</a></li>
                            <li>|</li>
                            <li><a href="<?=ROOT_URL;?>/tentangkami">Tentang Kami</a></li>
                            <li>|</li>
                            <li><a href="<?=ROOT_URL;?>/kodeetik">Kode Etik</a></li>
                            <li>|</li>
                            <li><a href="<?=ROOT_URL;?>/mitrakami">Mitra Kami</a></li>
                            <li>|</li>
                            <li><a href="<?=ROOT_URL;?>/syaratketentuan">Syarat dan Ketentuan</a></li>
                            <li>|</li>
                            <li><a href="<?=ROOT_URL;?>/produk">Produk dan Jasa</a></li>
                        </ul>
                    </div>
                    <div style="padding-top:15px;padding-left: 20px;color:white">
                         Informasi yang tersedia di<a href="<?=$this->baseUrl(); ?>" class="footnote"> www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
                         namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
                         Akses dan penggunaan situs ini tunduk pada Syarat dan Ketentuan &copy; 2009
                    </div>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </section>
    </div>
</footer>
<!-- End of Page footer -->