<footer id="down">
	<div class="container">
		<div class="row">
			<ul class="col_2 margin_top_15">
				<li>
					<strong>Produk</strong>
					<a href="" title="Awal">Awal</a>
				</li>
				<li>
					<a href="">Kenapa Hukumonline ?</a>
				</li>
				<li>
					<a href="">Tur</a>
				</li>
				<li>
					<a href="">Produk dan Jasa</a>
				</li>
				<li>
					<a href="">Daftar Gratis</a>
				</li>
			</ul>
			<ul class="col_2 margin_top_15">
				<li>
					<strong>Perusahaan</strong>
					<a href="" title="Awal">Tentang Kami</a>
				</li>
				<li>
					<a href="">Pelanggan</a>
				</li>
				<li>
					<a href="">Kode Etik</a>
				</li>
				<li>
					<a href="">Karir</a>
				</li>
			</ul>
			<ul class="col_2 margin_top_15">
				<li>
					<strong>Support</strong>
					<a href="" title="Awal">Help Center</a>
				</li>
				<li>
					<a href="">FAQ</a>
				</li>
				<li>
					<a href="">Feedback</a>
				</li>
			</ul>
			<ul class="col_2 margin_top_15">
				<li>
					<strong>Mitra</strong>
					<a href="" title="Awal">Dian Rakyat</a>
				</li>
				<li>
					<a href="">SHUBA Mitra Solusi</a>
				</li>
				<li>
					<a href="">Sekkab RI</a>
				</li>
				<li>
					<a href="">TAF</a>
				</li>
				<li>
					<a href="">USAID</a>
				</li>
			</ul>
			<ul class="col_2 margin_top_15">
				<li>
					<strong>Blog</strong>
					<a href="http://hukumonline.blogspot.com/" title="Hukumonline Blog">Blog Hukumonline</a>
				</li>
				<li>
					<a href="http://feeds.feedburner.com/hukumonline">Subscribe</a>
				</li>
			</ul>
			<ul class="col_2 margin_top_15 omega">
				<li>
					<strong>Get In Touch</strong>
					<a href="" title="Contact Us">Hubungi Kami</a>
				</li>
				<li>
					<a href="mailto:layanan@hukumonline.com">Layanan</a>
				</li>
				<li>
					<a href="mailto:marketing@hukumonline.com">Marketing</a>
				</li>
				<li>
					<a href="mailto:talks@hukumonline.com">Talks</a>
				</li>
			</ul>
		</div>
		<div class="row">
			<div class="col_12">
				<div class="phone">
				<strong>62-21-83701827</strong>
		         Informasi yang tersedia di <a href="<?=$this->baseUrl(); ?>" target="_blank">www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
		         namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
		         Akses dan penggunaan situs ini tunduk pada <a href="" target="_blank">Syarat dan Ketentuan</a> &copy;2009.
				</div>
			</div>
		</div>
	</div>
</footer>