<!-- S:Footer -->
<footer id="down">
    <div class="wrapper">
            <section class="column width8 first">
                <div class="colgroup leading">
					<dl class="column col_1 first">
						<dd>
							<strong>Produk</strong>
							<a href="" title="Awal">Awal</a>
						</dd>
						<dd>
							<a href="">Kenapa Kami?</a>
						</dd>
						<dd>
							<a href="">Tur</a>
						</dd>
						<dd>
							<a href="">Jasa Kami</a>
						</dd>
						<dd>
							<a href="">Daftar Gratis</a>
						</dd>
					</dl>
					<dl class="column col_1">
						<dd>
							<strong>Perusahaan</strong>
							<a href="" title="Awal">Tentang Kami</a>
						</dd>
						<dd>
							<a href="">Pelanggan</a>
						</dd>
						<dd>
							<a href="">Kode Etik</a>
						</dd>
						<dd>
							<a href="">Karir</a>
						</dd>
					</dl>
					<dl class="column col_1">
						<dd>
							<strong>Support</strong>
							<a href="" title="Awal">Help Center</a>
						</dd>
						<dd>
							<a href="">FAQ</a>
						</dd>
						<dd>
							<a href="">Feedback</a>
						</dd>
					</dl>
					<dl class="column col_1">
						<dd>
							<strong>Kontak</strong>
							<a href="" title="Contact Us">Hubungi Kami</a>
						</dd>
						<dd>
							<a href="mailto:layanan@hukumonline.com">Layanan</a>
						</dd>
						<dd>
							<a href="mailto:marketing@hukumonline.com">Marketing</a>
						</dd>
						<dd>
							<a href="mailto:talks@hukumonline.com">Talks</a>
						</dd>
					</dl>
					<dl class="column col_2">
						<dd class="icon">
						<a href="">twitter</a>
						</dd>
					</dl>
                </div>
                <div class="colgroup leading">
                	<div class="column width8 first">
						<div class="phone">
						<strong>62-21-83701827</strong>
				         Informasi yang tersedia di <a href="<?=$this->baseUrl(); ?>" target="_blank">www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
				         namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
				         Akses dan penggunaan situs ini tunduk pada <a href="" target="_blank">Syarat dan Ketentuan</a> &copy;2009.
						</div>
                	</div>
                </div>
        </section>
    </div>
</footer>
<!-- E:Footer -->