<!-- S:TOP BAR -->
<div id="topholid" align="center"> 
    <div id="topcontent"> 
    <?=$this->action('miniprofile','index','hol-site');?>		
	<div class="search_hol"> 
    	<form action="<?=$this->getRemoteSearchUrl();?>/id/dms/search/result" method="get"  class="search-holsearch"> 
	        <input class="input" name="keyword" id="keyword" onblur="blur_text('masukkan kata kunci','keyword');" onfocus="focus_text('masukkan kata kunci','keyword');" value="masukkan kata kunci" type="text">
			<input type="submit" class="btun" value="" /> 
 	    </form> 
	</div> 
	<div class="social_icon">
		<span>Ikuti kami:</span> 
		<a href="http://rss.hukumonline.com" target="_blank"><img src="<?=$this->cdn('images');?>/feed.png" alt="feed rss" /></a>
		<a href="http://www.facebook.com/pages/Hukumonlinecom/101301323243289" target="_blank"><img src="<?=$this->cdn('images');?>/facebook.png" alt="facebook" /></a>
		<a href="http://twitter.com/#!/hukumonline" target="_blank"><img src="<?=$this->cdn('images');?>/twitterhol.png" alt="twitter" /></a>
	</div>
    </div> 
</div> 
<!-- E:TOP BANNER -->
<!-- S:Header -->
<header id="up">
    <div class="wrapper">
        <section class="column first">
        	<div class="width8">
        	
			<!--/* OpenX Javascript Tag v2.8.5 */-->
			
			<!--/*
			  * The backup image section of this tag has been generated for use on a
			  * non-SSL page. If this tag is to be placed on an SSL page, change the
			  *   'http://openx.hukumonline.com/www/delivery/...'
			  * to
			  *   'https://openx.hukumonline.com/www/delivery/...'
			  *
			  * This noscript section of this tag only shows image banners. There
			  * is no width or height in these banners, so if you want these tags to
			  * allocate space for the ad before it shows, you will need to add this
			  * information to the <img> tag.
			  *
			  * If you do not want to deal with the intricities of the noscript
			  * section, delete the tag (from <noscript>... to </noscript>). On
			  * average, the noscript tag is called from less than 1% of internet
			  * users.
			  */-->
			
			<script type='text/javascript'><!--//<![CDATA[
			   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
			   var m3_r = Math.floor(Math.random()*99999999999);
			   if (!document.MAX_used) document.MAX_used = ',';
			   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
			   document.write ("?zoneid=19");
			   document.write ('&amp;cb=' + m3_r);
			   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
			   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
			   document.write ("&amp;loc=" + escape(window.location));
			   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
			   if (document.context) document.write ("&context=" + escape(document.context));
			   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
			   document.write ("'><\/scr"+"ipt>");
			//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a96423f9&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=19&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a96423f9' border='0' alt='' /></a></noscript>
        	
        	</div>
            <div class="colgroup">
                <div class="column width3 first">
                    <div id="judul"><a href="<?=ROOT_URL;?>"><img src="<?=$this->cdn('images');?>/logo_hukumonline.jpg" alt="hukumonline" /></a></div>
                </div>
                <div class="column width5">
                    <div class="topup">
                        <ul id="topnav">
                            <li><a href="http://en1.hukumonline.com" target="_blank">en.hukumonline.com</a></li>
                            <li><a href="http://hukumpedia.com" target="_blank">hukumpedia.com</a></li>
                            <li><a href="http://direktori.hukumonline.com" target="_blank">direktori.hukumonline.com</a></li>
                        </ul>
                    </div>
                    <div class="topdown">
                        <ul id="topnavi">
                            <li><a href="<?=$this->baseUrl();?>/faqs">Tentang Kami</a></li>
                            <li><a href="<?=$this->baseUrl();?>/faqs">Produk dan Jasa</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <div class="clean"></div>
        <div class="padding_top_10"></div>
        <nav style="width:100%;background:#00008B;">
        	<div class="align-left">
            	<?php 
            	$date = date('Y-m-d');
				$array_hari = array(1=>"Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu");
				$lang = array("Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "Nopember", "Desember");
				$hari = $array_hari[date("N",strtotime(date('Y-m-d H:i:s')))];
				$yy = substr($date, 0, 4);
				$mm = substr($date, 5, 2);
				$dd = substr($date, 8, 10);
				$today = $hari . ', '.$dd." ".$lang[$mm-1]." ".$yy;
				$time = date("H:i");
				?>
				<div style="vertical-align:middle;padding:8px;color:#fff;font:bold;">
					<?=$today;?> &raquo; <?=$time;?> WIB
				</div>
        	</div>
        	<div class="align-right">
	            <div id="menu">
				    <ul class="sf-menu">
				        <li class="current"><a href="<?=ROOT_URL;?>">Awal</a></li>
				        <li><a href="<?=ROOT_URL;?>/warta">Berita</a>
				        <? if ($this->menuFolder) : ?>
						<ul>
						
						    <?
						    for ($i=0;$i<count($this->menuFolder);$i++)
						    {
						    $json = new Zend_Json();
						    $aData = $json->decode($this->menuFolder[$i]['cmsParams']);
						    ?>
						    <li>
						    <a href="<?=ROOT_URL;?>/page/<?=$aData['st']?>"><?=$this->menuFolder[$i]['title']?></a>
						    <?=$this->action('getmenuchild','widgets_content','hol-site',array('node'=>$this->menuFolder[$i]['guid']))?>
						    </li>
						    <? } ?>
						
						</ul>
						<? endif; ?>
						</li>
				        <li><a href="<?=ROOT_URL;?>/pusatdata">Pusat Data</a></li>
				        <li><a href="<?=ROOT_URL;?>/klinik">Klinik</a>
				        <ul>
				            <? for($i=0; $i<$this->numberOfRows;$i++) { ?>
				                <li><a href="<?=ROOT_URL;?>/klinik/kategori/<?=$this->data[$i][1]; ?>" title="<?=$this->data[$i][0]; ?>"><?=$this->data[$i][0]; ?></a></li>
				            <? } ?>
				        </ul>
				        </li>
				        <li><a href="<?=ROOT_URL;?>/talks">Talks</a>
				        <ul>
				        	<li><a href="<?=ROOT_URL;?>/talks/events">Upcoming events</a></li>
				        </ul>
				        </li>                                                            
				        <li><a href="<?=ROOT_URL;?>/karir">Karir</a></li>
				        <li><a href="<?=ROOT_URL;?>/FAQ">FAQ</a></li>
				    </ul>
	            </div>
        	</div>
        </nav>
    </div>
</header>
<!-- E:Header -->
<div class="clean"></div>
<div class="margin_top_40"></div>