<div id="topholid" align="center"> 
    <div id="topcontent"> 
	    <?=$this->action('miniprofile80','index','hol-site');?>		
	    <div class="search_hol">
	    	<form action="<?=$this->getRemoteSearchUrl();?>/id/dms/search/result" method="get"  class="search-holsearch"> 
		        <input class="input" name="keyword" id="keyword" onblur="blur_text('masukkan kata kunci','keyword');" onfocus="focus_text('masukkan kata kunci','keyword');" value="masukkan kata kunci" type="text">
				<input type="submit" class="btun" value="" /> 
	 	    </form> 
	    </div>
	    <div class="social_icon">
			<span>Ikuti kami:</span> 
			<a href="http://rss.hukumonline.com" target="_blank"><img src="<?=$this->cdn('images');?>/feed.png" alt="feed rss" /></a>
			<a href="http://www.facebook.com/pages/Hukumonlinecom/101301323243289" target="_blank"><img src="<?=$this->cdn('images');?>/facebook.png" alt="facebook" /></a>
			<a href="http://twitter.com/#!/hukumonline" target="_blank"><img src="<?=$this->cdn('images');?>/twitterhol.png" alt="twitter" /></a>
	    </div>
    </div> 
</div> 
<div class="clear"></div>
<div class="padding_top_45"></div>
<header>
	<div class="container">
		<div class="row">
			<div class="col_3 clearleft">
				<div id="judul"><a href="<?=ROOT_URL;?>"><img src="<?=$this->cdn('images');?>/logo_hukumonline.jpg" alt="hukumonline" /></a></div>
			</div>
			<div class="col_3">
				q
			</div>
			<div class="col_6 omega">
				<div class="topup">
	                <ul id="topnav">
	                    <li><a href="http://en.hukumonline.com" target="_blank">en.hukumonline.com</a></li>
	                    <li><a href="http://hukumpedia.com" target="_blank">hukumpedia.com</a></li>
	                    <li><a href="http://direktori.hukumonline.com" target="_blank">direktori.hukumonline.com</a></li>
	                </ul>
				</div>
				<div class="topdown">
				menu
				</div>
			</div>
		</div>
	</div>
</header>	