<div id="top-bar">
	<div class="container">
	  <div class="row">
	    <div class="col_3">
			<div class="top-search">
				<form id="searchForm" method="post" action="<?=$this->getRemoteSearchUrl();?>/id/dms/search/result">
				    <input class="" name="keyword" id="keyword" onblur="blur_text('masukkan kata kunci','keyword');" onfocus="focus_text('masukkan kata kunci','keyword');" value="masukkan kata kunci" type="text">
				</form>
			</div>

		</div>
		<div class="col_9 omega">
			<div class="col_6 margin_top_5">
				<div class="social_icon">
					<span>Find us on:</span> 
					<a href="http://rss.hukumonline.com" target="_blank"><img src="<?=$this->cdn('images');?>/feed.png" alt="feed rss" /></a>
					<a href="http://www.facebook.com/pages/Hukumonlinecom/101301323243289" target="_blank"><img src="<?=$this->cdn('images');?>/facebook.png" alt="facebook" /></a>
					<a href="http://twitter.com/#!/hukumonline" target="_blank"><img src="<?=$this->cdn('images');?>/twitterhol.png" alt="twitter" /></a>
				</div>
			</div>
			<div class="col_3 last">
				<?=$this->action('miniprofile','index','hol-site');?>
			</div>
		</div>
	  </div>
	</div>
	<div class="clear"></div>
</div>