<header id="up">
    <div class="wrapper">
        <section class="column width8 first">
            <div class="colgroup leading">
                <div class="kolom widthcontent1 first">
                    <div id="judul"><a href="<?=ROOT_URL;?>"><img src="<?=$this->cdn('images');?>/logo_hukumonline.jpg" alt="hukumonline" /></a></div>
                </div>
                <div class="kolom widthcontent2 pembatas1" style="width:235px;">
                    <div class="ta-right" style="padding-right:22px;padding-top: 5px;">[ <a href="" class="bb">index</a> ]</div>
                    <?=$this->action('aktual','widgets_content','hol-site');?>
                </div>
                <div class="kolom widthcontent3" style="border-left: 1px solid #cecece;">
                    <div class="st1" style="width: 503px;">
                        <div class="headerMenu">
                            <ul>
                                <li><a href="http://en1.hukumonline.com">en.hukumonline.com</a></li>
                                <li>|</li>
                                <li><a href="http://hukumpedia.com">hukumpedia.com</a></li>
                                <li>|</li>
                                <li><a href="http://forum.hukumonline.com">forum.hukumonline.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="st2" style="width: 503px;">
                        <ul id="headerMenu_b">
                            <li><a href="<?=$this->baseUrl();?>/faqs">FAQs</a></li>
                            <li><a href="<?=$this->baseUrl();?>/direktori">Direktori</a></li>
                            <li><a href="<?=$this->baseUrl();?>/talks">Talks</a></li>
                            <li><a href="<?=$this->baseUrl();?>/klinik">Klinik</a></li>
                            <li><a href="<?=$this->baseUrl();?>/pusatdata">Pusat Data</a></li>
                            <li><a href="<?=$this->baseUrl();?>/warta">Berita</a></li>
                            <li><a href="<?=ROOT_URL;?>">Awal</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="clear">&nbsp;</div>
</header>