<!-- Page content -->
<div id="page">
    <div class="wrapper">
        <section class="column first">
        	<div class="colgroup">
        		<div class="kolom widthcontent7 first">
        		
					<!--/* OpenX Javascript Tag v2.8.5 */-->
					
					<!--/*
					  * The backup image section of this tag has been generated for use on a
					  * non-SSL page. If this tag is to be placed on an SSL page, change the
					  *   'http://openx.hukumonline.com/www/delivery/...'
					  * to
					  *   'https://openx.hukumonline.com/www/delivery/...'
					  *
					  * This noscript section of this tag only shows image banners. There
					  * is no width or height in these banners, so if you want these tags to
					  * allocate space for the ad before it shows, you will need to add this
					  * information to the <img> tag.
					  *
					  * If you do not want to deal with the intricities of the noscript
					  * section, delete the tag (from <noscript>... to </noscript>). On
					  * average, the noscript tag is called from less than 1% of internet
					  * users.
					  */-->
					
					<script type='text/javascript'><!--//<![CDATA[
					   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
					   var m3_r = Math.floor(Math.random()*99999999999);
					   if (!document.MAX_used) document.MAX_used = ',';
					   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
					   document.write ("?zoneid=20");
					   document.write ('&amp;cb=' + m3_r);
					   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
					   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
					   document.write ("&amp;loc=" + escape(window.location));
					   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
					   if (document.context) document.write ("&context=" + escape(document.context));
					   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
					   document.write ("'><\/scr"+"ipt>");
					//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=af74b240&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=20&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=af74b240' border='0' alt='' /></a></noscript>
        		
        		</div>
        		<div class="kolom widthcontent8">
        		
					<!--/* OpenX Javascript Tag v2.8.5 */-->
					
					<!--/*
					  * The backup image section of this tag has been generated for use on a
					  * non-SSL page. If this tag is to be placed on an SSL page, change the
					  *   'http://openx.hukumonline.com/www/delivery/...'
					  * to
					  *   'https://openx.hukumonline.com/www/delivery/...'
					  *
					  * This noscript section of this tag only shows image banners. There
					  * is no width or height in these banners, so if you want these tags to
					  * allocate space for the ad before it shows, you will need to add this
					  * information to the <img> tag.
					  *
					  * If you do not want to deal with the intricities of the noscript
					  * section, delete the tag (from <noscript>... to </noscript>). On
					  * average, the noscript tag is called from less than 1% of internet
					  * users.
					  */-->
					
					<script type='text/javascript'><!--//<![CDATA[
					   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
					   var m3_r = Math.floor(Math.random()*99999999999);
					   if (!document.MAX_used) document.MAX_used = ',';
					   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
					   document.write ("?zoneid=21");
					   document.write ('&amp;cb=' + m3_r);
					   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
					   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
					   document.write ("&amp;loc=" + escape(window.location));
					   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
					   if (document.context) document.write ("&context=" + escape(document.context));
					   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
					   document.write ("'><\/scr"+"ipt>");
					//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a14e40ce&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=21&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a14e40ce' border='0' alt='' /></a></noscript>
        		
        		</div>
        	</div>
        	<div class="clean"></div>
        	<div class="padding_top_10"></div>
            <div class="colgroup">
                <div class="kolom widthcontent4 first">
                    <div class="colgroup">
                        <div class="kolom widthcontent1 first">
                            <?=$this->action('pusatdata','widgets_content','hol-site');?>
                            <div class="padding_top_5"></div>
                            <div class="widthcontent_custom_2">
								<!--/* OpenX Javascript Tag v2.8.5 */-->
								
								<!--/*
								  * The backup image section of this tag has been generated for use on a
								  * non-SSL page. If this tag is to be placed on an SSL page, change the
								  *   'http://openx.hukumonline.com/www/delivery/...'
								  * to
								  *   'https://openx.hukumonline.com/www/delivery/...'
								  *
								  * This noscript section of this tag only shows image banners. There
								  * is no width or height in these banners, so if you want these tags to
								  * allocate space for the ad before it shows, you will need to add this
								  * information to the <img> tag.
								  *
								  * If you do not want to deal with the intricities of the noscript
								  * section, delete the tag (from <noscript>... to </noscript>). On
								  * average, the noscript tag is called from less than 1% of internet
								  * users.
								  */-->
								
								<script type='text/javascript'><!--//<![CDATA[
								   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
								   var m3_r = Math.floor(Math.random()*99999999999);
								   if (!document.MAX_used) document.MAX_used = ',';
								   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
								   document.write ("?zoneid=22");
								   document.write ('&amp;cb=' + m3_r);
								   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
								   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
								   document.write ("&amp;loc=" + escape(window.location));
								   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
								   if (document.context) document.write ("&context=" + escape(document.context));
								   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
								   document.write ("'><\/scr"+"ipt>");
								//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a7790006&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=22&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a7790006' border='0' alt='' /></a></noscript>
                            
                            </div>
                            <div class="padding_top_5"></div>
                            <div class="widthcontent_custom_2">
								<!--/* OpenX Javascript Tag v2.8.5 */-->
								
								<!--/*
								  * The backup image section of this tag has been generated for use on a
								  * non-SSL page. If this tag is to be placed on an SSL page, change the
								  *   'http://openx.hukumonline.com/www/delivery/...'
								  * to
								  *   'https://openx.hukumonline.com/www/delivery/...'
								  *
								  * This noscript section of this tag only shows image banners. There
								  * is no width or height in these banners, so if you want these tags to
								  * allocate space for the ad before it shows, you will need to add this
								  * information to the <img> tag.
								  *
								  * If you do not want to deal with the intricities of the noscript
								  * section, delete the tag (from <noscript>... to </noscript>). On
								  * average, the noscript tag is called from less than 1% of internet
								  * users.
								  */-->
								
								<script type='text/javascript'><!--//<![CDATA[
								   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
								   var m3_r = Math.floor(Math.random()*99999999999);
								   if (!document.MAX_used) document.MAX_used = ',';
								   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
								   document.write ("?zoneid=23");
								   document.write ('&amp;cb=' + m3_r);
								   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
								   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
								   document.write ("&amp;loc=" + escape(window.location));
								   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
								   if (document.context) document.write ("&context=" + escape(document.context));
								   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
								   document.write ("'><\/scr"+"ipt>");
								//]]>--></script> 
								                           
                            </div>
                        </div>
                        <div class="kolom widthcontent_custom_1">
                            <?=$this->action('klinik','widgets_content','hol-site');?>
                        </div>
                    </div>
                    <div class="colgroup padding_top_5 ta-center">
                    
						<!--/* OpenX Javascript Tag v2.8.5 */-->
						
						<!--/*
						  * The backup image section of this tag has been generated for use on a
						  * non-SSL page. If this tag is to be placed on an SSL page, change the
						  *   'http://openx.hukumonline.com/www/delivery/...'
						  * to
						  *   'https://openx.hukumonline.com/www/delivery/...'
						  *
						  * This noscript section of this tag only shows image banners. There
						  * is no width or height in these banners, so if you want these tags to
						  * allocate space for the ad before it shows, you will need to add this
						  * information to the <img> tag.
						  *
						  * If you do not want to deal with the intricities of the noscript
						  * section, delete the tag (from <noscript>... to </noscript>). On
						  * average, the noscript tag is called from less than 1% of internet
						  * users.
						  */-->
						
						<script type='text/javascript'><!--//<![CDATA[
						   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
						   var m3_r = Math.floor(Math.random()*99999999999);
						   if (!document.MAX_used) document.MAX_used = ',';
						   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
						   document.write ("?zoneid=24");
						   document.write ('&amp;cb=' + m3_r);
						   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
						   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
						   document.write ("&amp;loc=" + escape(window.location));
						   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
						   if (document.context) document.write ("&context=" + escape(document.context));
						   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
						   document.write ("'><\/scr"+"ipt>");
						//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a48b5c5e&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=24&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a48b5c5e' border='0' alt='' /></a></noscript>
                    
                    </div>
                    <div class="colgroup">
                        <div class="kolom widthcontent_custom_2 padding_top_15 first">
                            <?=$this->action('kolom','widgets_content','hol-site');?>
                            <div class="padding_top_15"></div>
                            <?=$this->action('talk','widgets_content','hol-site');?>
                            <div class="padding_top_15"></div>
                            <?=$this->action('view','manager','polling');?>
                        </div>
                        <div class="kolom widthcontent_custom_1 padding_top_15">
                            <?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb18','title'=>'Tajuk'));?>
                            <div class="padding_top_15"></div>
                            <?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb9','title'=>'Info'));?>
                            <div class="padding_top_15"></div>
                            <?=$this->action('suarapembaca','widgets_content','hol-site');?>
                            <div class="padding_top_15"></div>
                            <?=$this->action('komunitas','widgets_content','hol-site');?>
                            <div class="padding_top_15"></div>
                            <div id="showDiv1" style="width:100%;text-align:center;">
                            <?=$this->action('browse','manager','agenda');?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="kolom widthcontent3 bl_grey padding_left_10">
                	<?=$this->action('aktual','widgets_content','hol-site');?>
                	<div class="padding_top_5"></div>
                    <?=$this->action('utama','widgets_content','hol-site');?>
                    <div class="padding_top_10"></div>
                    <?=$this->action('terbaru','widgets_content','hol-site',array('node'=>'lt4c5a39d28cac9'));?>
                    
                    <div class="align-left widthcontent_custom_7 first">
                    
						<!--/* OpenX Javascript Tag v2.8.5 */-->
						
						<!--/*
						  * The backup image section of this tag has been generated for use on a
						  * non-SSL page. If this tag is to be placed on an SSL page, change the
						  *   'http://openx.hukumonline.com/www/delivery/...'
						  * to
						  *   'https://openx.hukumonline.com/www/delivery/...'
						  *
						  * This noscript section of this tag only shows image banners. There
						  * is no width or height in these banners, so if you want these tags to
						  * allocate space for the ad before it shows, you will need to add this
						  * information to the <img> tag.
						  *
						  * If you do not want to deal with the intricities of the noscript
						  * section, delete the tag (from <noscript>... to </noscript>). On
						  * average, the noscript tag is called from less than 1% of internet
						  * users.
						  */-->
						
						<script type='text/javascript'><!--//<![CDATA[
						   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
						   var m3_r = Math.floor(Math.random()*99999999999);
						   if (!document.MAX_used) document.MAX_used = ',';
						   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
						   document.write ("?zoneid=25");
						   document.write ('&amp;cb=' + m3_r);
						   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
						   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
						   document.write ("&amp;loc=" + escape(window.location));
						   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
						   if (document.context) document.write ("&context=" + escape(document.context));
						   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
						   document.write ("'><\/scr"+"ipt>");
						//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a398a76a&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=25&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a398a76a' border='0' alt='' /></a></noscript>
                    
                    </div>
                    <div class="align-right widthcontent9">
                    
						<!--/* OpenX Javascript Tag v2.8.5 */-->
						
						<!--/*
						  * The backup image section of this tag has been generated for use on a
						  * non-SSL page. If this tag is to be placed on an SSL page, change the
						  *   'http://openx.hukumonline.com/www/delivery/...'
						  * to
						  *   'https://openx.hukumonline.com/www/delivery/...'
						  *
						  * This noscript section of this tag only shows image banners. There
						  * is no width or height in these banners, so if you want these tags to
						  * allocate space for the ad before it shows, you will need to add this
						  * information to the <img> tag.
						  *
						  * If you do not want to deal with the intricities of the noscript
						  * section, delete the tag (from <noscript>... to </noscript>). On
						  * average, the noscript tag is called from less than 1% of internet
						  * users.
						  */-->
						
						<script type='text/javascript'><!--//<![CDATA[
						   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
						   var m3_r = Math.floor(Math.random()*99999999999);
						   if (!document.MAX_used) document.MAX_used = ',';
						   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
						   document.write ("?zoneid=26");
						   document.write ('&amp;cb=' + m3_r);
						   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
						   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
						   document.write ("&amp;loc=" + escape(window.location));
						   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
						   if (document.context) document.write ("&context=" + escape(document.context));
						   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
						   document.write ("'><\/scr"+"ipt>");
						//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a961dd7d&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=26&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a961dd7d' border='0' alt='' /></a></noscript>
                    
                    </div>
                    <div class="clean"></div>
                    
                    <?=$this->action('hfoto','widgets_content','hol-site');?>
                    <div class="align-left widthcontent_custom_4 first">
                        <?=$this->action('fokus','widgets_content','hol-site');?>
                    </div>
                    <div class="align-right widthcontent_custom_5">
                        <?=$this->action('isuhangat','widgets_content','hol-site');?>
                    </div>
                    <div class="clear">&nbsp;</div>

                    <div class="align-left widthcontent_custom_3 padding_top_15 first">
                        <?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb12','title'=>'Tokoh'));?>
                    </div>
                    <div class="align-right widthcontent_custom_5 padding_top_15">
                        <?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb14','title'=>'Jeda'));?>
                    </div>
                    <div class="clear">&nbsp;</div>
					<div class="clean"></div>
                    <?=$this->action('resensi','widgets_content','hol-site');?>
                    <div class="clear">&nbsp;</div>
					<div class="clean"></div>
                    <?//=$this->action('column','widgets_content','hol-site');?>

                </div>
                <div class="clear">&nbsp;</div>
            </div>
            <div class="clear">&nbsp;</div>
            <div class="width8">
            
				<!--/* OpenX Javascript Tag v2.8.5 */-->
				
				<!--/*
				  * The backup image section of this tag has been generated for use on a
				  * non-SSL page. If this tag is to be placed on an SSL page, change the
				  *   'http://openx.hukumonline.com/www/delivery/...'
				  * to
				  *   'https://openx.hukumonline.com/www/delivery/...'
				  *
				  * This noscript section of this tag only shows image banners. There
				  * is no width or height in these banners, so if you want these tags to
				  * allocate space for the ad before it shows, you will need to add this
				  * information to the <img> tag.
				  *
				  * If you do not want to deal with the intricities of the noscript
				  * section, delete the tag (from <noscript>... to </noscript>). On
				  * average, the noscript tag is called from less than 1% of internet
				  * users.
				  */-->
				
				<script type='text/javascript'><!--//<![CDATA[
				   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
				   var m3_r = Math.floor(Math.random()*99999999999);
				   if (!document.MAX_used) document.MAX_used = ',';
				   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
				   document.write ("?zoneid=27");
				   document.write ('&amp;cb=' + m3_r);
				   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
				   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
				   document.write ("&amp;loc=" + escape(window.location));
				   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
				   if (document.context) document.write ("&context=" + escape(document.context));
				   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
				   document.write ("'><\/scr"+"ipt>");
				//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a8f917e9&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=27&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a8f917e9' border='0' alt='' /></a></noscript>
            
            </div>
        </section>
    </div>
</div>
<!-- End of Page content -->
