<div class="mprofile textright margin_top_5">
    <?
    $auth = Zend_Auth::getInstance();
    if ($auth->hasIdentity()) :
    ?>
    <a href="#" onclick="window.location='<?=$this->profile;?>';return false;"><?=$this->username; ?></a><a href="#" onclick="window.location='<?=$this->logoutUrl;?>';return false;">logout</a>
    <?  else : ?>
    <a href="#" onclick="window.location='<?=$this->signUp;?>';return false;">Daftar</a><a href="#" onclick="window.location='<?=$this->loginUrl;?>';return false;">Masuk</a>
    <? endif; ?>
</div>
